"""
Django settings for ask_video project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url


# DRY principle: Centralized management of environment variable defaults
class DefaultSettings:
    """Centralized management of default settings (DRY principle)"""

    # Database
    DATABASE_URL = "postgres://postgres:postgres@localhost:5432/postgres"

    # Celery
    CELERY_BROKER_URL = "redis://localhost:6379/0"
    CELERY_RESULT_BACKEND = "redis://localhost:6379/0"

    # Security
    SECRET_KEY = "django-insecure-644978l%$qgjwpo$w!5i7l#y(m&h)e$u#3en_a%ln^4!js$-*+"

    # CORS
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

    # Feature flags
    ENABLE_SIGNUP = True

    # Storage
    USE_S3_STORAGE = False

    # Email
    FRONTEND_URL = "http://localhost:3000"
    DEFAULT_FROM_EMAIL = "noreply@askvideo.local"
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_HOST = ""
    EMAIL_PORT = 587
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""
    EMAIL_USE_TLS = True


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", DefaultSettings.SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "corsheaders",
    "app",
    "anymail",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ask_video.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ask_video.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        os.environ.get("DATABASE_URL", DefaultSettings.DATABASE_URL)
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Chicago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (Uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "app.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "app.common.authentication.CookieJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Security: Disable Browsable API in production
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Ask Video API",
    "DESCRIPTION": "API documentation for Ask Video application",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "AUTHENTICATION_WHITELIST": [
        "app.common.authentication.CookieJWTAuthentication",
    ],
    "SCHEMA_PATH_PREFIX": "/api/",
}

_cors_allowed_origins_env = os.environ.get("CORS_ALLOWED_ORIGINS")
if _cors_allowed_origins_env:
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in _cors_allowed_origins_env.split(",")
        if origin.strip()
    ]
else:
    CORS_ALLOWED_ORIGINS = DefaultSettings.CORS_ALLOWED_ORIGINS

# Celery Configuration
CELERY_BROKER_URL = os.environ.get(
    "CELERY_BROKER_URL", DefaultSettings.CELERY_BROKER_URL
)
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND", DefaultSettings.CELERY_RESULT_BACKEND
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "America/Chicago"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes

# Feature flags
ENABLE_SIGNUP = os.environ.get("ENABLE_SIGNUP", "true").lower() == "true"

# Storage configuration
USE_S3_STORAGE = (
    os.environ.get("USE_S3_STORAGE", str(DefaultSettings.USE_S3_STORAGE)).lower()
    == "true"
)

FRONTEND_URL = os.environ.get("FRONTEND_URL", DefaultSettings.FRONTEND_URL)
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", DefaultSettings.DEFAULT_FROM_EMAIL
)
EMAIL_BACKEND = DefaultSettings.EMAIL_BACKEND

USE_MAILGUN = os.environ.get("USE_MAILGUN", "false").lower() == "true"

if USE_MAILGUN:
    EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
    mailgun_sender_domain = os.environ.get("MAILGUN_SENDER_DOMAIN", "")
    ANYMAIL = {
        "MAILGUN_API_KEY": os.environ.get("MAILGUN_API_KEY"),
        "MAILGUN_SENDER_DOMAIN": mailgun_sender_domain,
    }
    if "DEFAULT_FROM_EMAIL" not in os.environ and mailgun_sender_domain:
        DEFAULT_FROM_EMAIL = f"Ask Video <noreply@{mailgun_sender_domain}>"
else:
    EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", DefaultSettings.EMAIL_BACKEND)
    EMAIL_HOST = os.environ.get("EMAIL_HOST", DefaultSettings.EMAIL_HOST)
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", DefaultSettings.EMAIL_PORT))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", DefaultSettings.EMAIL_HOST_USER)
    EMAIL_HOST_PASSWORD = os.environ.get(
        "EMAIL_HOST_PASSWORD", DefaultSettings.EMAIL_HOST_PASSWORD
    )
    EMAIL_USE_TLS = (
        os.environ.get("EMAIL_USE_TLS", str(DefaultSettings.EMAIL_USE_TLS)).lower()
        == "true"
    )
