-- Minimal columns with the deletion relationships from 0001_new_schema.sql
-- and the subsequent group-to-course rename. Shared by API and Python tests.
CREATE TABLE videos (id integer PRIMARY KEY, user_id text NOT NULL, status text NOT NULL DEFAULT 'completed', file text NOT NULL DEFAULT '');
CREATE TABLE plog_build_jobs (
    id integer PRIMARY KEY, video_id integer REFERENCES videos ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'ready', created_at timestamptz NOT NULL DEFAULT now(),
    input_tokens integer NOT NULL DEFAULT 0, output_tokens integer NOT NULL DEFAULT 0,
    error_message text NOT NULL DEFAULT ''
);
CREATE TABLE plog_summary_nodes (
    id integer PRIMARY KEY, video_id integer REFERENCES videos ON DELETE CASCADE,
    parent_id integer REFERENCES plog_summary_nodes ON DELETE CASCADE,
    level smallint NOT NULL DEFAULT 0, text text NOT NULL DEFAULT '',
    start_sec double precision NOT NULL DEFAULT 0, end_sec double precision NOT NULL DEFAULT 0
);
CREATE TABLE plog_concepts (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    video_id integer NOT NULL REFERENCES videos ON DELETE CASCADE,
    label text NOT NULL DEFAULT '', node_type text NOT NULL DEFAULT 'concept',
    intro_sec double precision NOT NULL DEFAULT 0, source_quote text NOT NULL DEFAULT '',
    embedding jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (label, video_id)
);
CREATE TABLE plog_edges (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    video_id integer NOT NULL REFERENCES videos ON DELETE CASCADE,
    source_id integer NOT NULL REFERENCES plog_concepts ON DELETE CASCADE,
    target_id integer NOT NULL REFERENCES plog_concepts ON DELETE CASCADE,
    edge_type text NOT NULL DEFAULT 'presentation_order', quote text NOT NULL DEFAULT '',
    validation_status text NOT NULL DEFAULT 'generated', created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (edge_type, source_id, target_id, video_id)
);
CREATE TABLE plog_learning_objects (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    concept_id integer NOT NULL UNIQUE REFERENCES plog_concepts ON DELETE CASCADE,
    opening_question text NOT NULL DEFAULT '', hint_ladder jsonb NOT NULL DEFAULT '[]',
    misconceptions jsonb NOT NULL DEFAULT '[]', canonical_order jsonb NOT NULL DEFAULT '[]',
    worked_examples jsonb NOT NULL DEFAULT '[]', waypoints jsonb NOT NULL DEFAULT '[]',
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE learner_concept_states (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    concept_id integer NOT NULL REFERENCES plog_concepts ON DELETE CASCADE,
    user_id text NOT NULL DEFAULT 'owner', reached boolean NOT NULL DEFAULT false,
    hint_index smallint NOT NULL DEFAULT 0, last_grade text NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT false, UNIQUE (concept_id, user_id)
);
CREATE TABLE video_tags (id integer PRIMARY KEY, video_id integer REFERENCES videos ON DELETE CASCADE);
CREATE TABLE video_course_members (id integer PRIMARY KEY, video_id integer REFERENCES videos ON DELETE CASCADE);
-- These two tables deliberately have no FK to videos and require explicit cleanup.
CREATE TABLE scene_embeddings (id integer PRIMARY KEY, video_id integer);
CREATE TABLE mcp_idempotency_records (id integer PRIMARY KEY, user_id text, resource_id bigint, action text);

INSERT INTO videos (id, user_id) VALUES (10, 'owner'), (20, 'outsider');
INSERT INTO plog_build_jobs (id, video_id) VALUES (1, 10), (2, 20);
INSERT INTO plog_summary_nodes (id, video_id, parent_id) VALUES (1, 10, NULL), (2, 20, NULL), (3, 10, 1);
INSERT INTO plog_concepts (id, video_id) VALUES (1, 10), (2, 20);
INSERT INTO plog_edges (id, video_id, source_id, target_id) VALUES (1, 10, 1, 1), (2, 20, 2, 2);
INSERT INTO plog_learning_objects (id, concept_id) VALUES (1, 1), (2, 2);
INSERT INTO learner_concept_states (id, concept_id) VALUES (1, 1), (2, 2);
INSERT INTO video_tags VALUES (1, 10), (2, 20);
INSERT INTO video_course_members VALUES (1, 10), (2, 20);
INSERT INTO scene_embeddings VALUES (1, 10), (2, 20);
INSERT INTO mcp_idempotency_records VALUES (1, 'owner', 10, 'request_video_upload'), (2, 'outsider', 20, 'create_youtube_video');
