"""
Django settings for videoq project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured


# ── AWS Secrets Manager サポート ─────────────────────────────────────────────
# Lambda 環境では DB_SECRET_ARN / APP_SECRET_ARN を環境変数で渡す。
# settings モジュール読み込み時に 1 度だけ取得し、環境変数に展開する。
# (Lambda コンテナは再利用されるため実質的にキャッシュされる)

def _load_aws_secret(secret_arn: str) -> dict:
    import boto3
    client = boto3.client("secretsmanager")
    return json.loads(
        client.get_secret_value(SecretId=secret_arn)["SecretString"]
    )


_db_secret_arn = os.environ.get("DB_SECRET_ARN")
if _db_secret_arn:
    _db = _load_aws_secret(_db_secret_arn)
    if "DATABASE_URL" in _db:
        # Neon 形式: {"DATABASE_URL": "postgresql://...@neon.tech/...?sslmode=require"}
        os.environ.setdefault("DATABASE_URL", _db["DATABASE_URL"])
    else:
        # RDS 管理シークレット形式 (後方互換): username / password / host / port / dbname
        os.environ.setdefault(
            "DATABASE_URL",
            "postgresql://{username}:{password}@{host}:{port}/{dbname}".format(
                username=_db["username"],
                password=_db["password"],
                host=os.environ.get("DB_HOST", _db.get("host", "localhost")),
                port=os.environ.get("DB_PORT", str(_db.get("port", 5432))),
                dbname=os.environ.get("DB_NAME", _db.get("dbname", "videoq")),
            ),
        )

_app_secret_arn = os.environ.get("APP_SECRET_ARN")
_app_secrets: dict = {}
if _app_secret_arn:
    _app_secrets = _load_aws_secret(_app_secret_arn)
    for _k, _v in _app_secrets.items():
        os.environ.setdefault(_k, str(_v))
# ── END: AWS Secrets Manager サポート ────────────────────────────────────────


class DefaultSettings:
    """Centralized management of default settings"""

    # Database
    DATABASE_URL = "postgres://postgres:postgres@localhost:5432/postgres"

    # Celery
    CELERY_BROKER_URL = "redis://localhost:6379/0"
    CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
    CACHE_URL = "redis://localhost:6379/0"

    # Security
    SECRET_KEY = "django-insecure-644978l%$qgjwpo$w!5i7l#y(m&h)e$u#3en_a%ln^4!js$-*+"
    DEFAULT_VIDEO_LIMIT = 5
    MAX_VIDEO_UPLOAD_SIZE_MB = 500
    FFPROBE_VALIDATION_TIMEOUT_SECONDS = 10
    FFMPEG_PROCESS_TIMEOUT_SECONDS = 120
    MEDIA_PROCESS_CPU_TIME_LIMIT_SECONDS = 30
    MEDIA_PROCESS_MEMORY_LIMIT_MB = 2048
    MEDIA_PROCESS_OUTPUT_FILE_SIZE_LIMIT_MB = 512
    # CORS
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

    # Feature flags
    ENABLE_SIGNUP = True

    # Storage
    USE_S3_STORAGE = False

    # Email
    FRONTEND_URL = "http://localhost:3000"
    DEFAULT_FROM_EMAIL = "noreply@videoq.local"
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_HOST = ""
    EMAIL_PORT = 587
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""
    EMAIL_USE_TLS = True

    # Embedding configuration
    EMBEDDING_PROVIDER = "openai"  # openai or ollama
    EMBEDDING_MODEL = (
        "text-embedding-3-small"  # Default embedding model (provider-agnostic)
    )
    OLLAMA_BASE_URL = "http://host.docker.internal:11434"  # Ollama server URL

    # LLM configuration
    LLM_PROVIDER = "openai"  # openai or ollama
    LLM_MODEL = "gpt-4o-mini"  # Default LLM model (provider-agnostic)

    # Whisper configuration
    WHISPER_BACKEND = "openai"  # openai or local


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
DJANGO_ENV = os.environ.get("DJANGO_ENV", "development").lower()
IS_PRODUCTION = DJANGO_ENV == "production"

_secret_key = os.environ.get("SECRET_KEY")
if IS_PRODUCTION:
    if _secret_key is None:
        raise ImproperlyConfigured(
            "SECRET_KEY must be set when DJANGO_ENV=production."
        )
    if not _secret_key.strip():
        raise ImproperlyConfigured(
            "SECRET_KEY must not be blank when DJANGO_ENV=production."
        )

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _secret_key if _secret_key else DefaultSettings.SECRET_KEY
DEFAULT_VIDEO_LIMIT = int(
    os.environ.get(
        "DEFAULT_VIDEO_LIMIT",
        str(DefaultSettings.DEFAULT_VIDEO_LIMIT),
    )
)
MAX_VIDEO_UPLOAD_SIZE_MB = int(
    os.environ.get(
        "MAX_VIDEO_UPLOAD_SIZE_MB",
        str(DefaultSettings.MAX_VIDEO_UPLOAD_SIZE_MB),
    )
)
MAX_VIDEO_UPLOAD_SIZE_BYTES = MAX_VIDEO_UPLOAD_SIZE_MB * 1024 * 1024
FFPROBE_VALIDATION_TIMEOUT_SECONDS = int(
    os.environ.get(
        "FFPROBE_VALIDATION_TIMEOUT_SECONDS",
        str(DefaultSettings.FFPROBE_VALIDATION_TIMEOUT_SECONDS),
    )
)
FFMPEG_PROCESS_TIMEOUT_SECONDS = int(
    os.environ.get(
        "FFMPEG_PROCESS_TIMEOUT_SECONDS",
        str(DefaultSettings.FFMPEG_PROCESS_TIMEOUT_SECONDS),
    )
)
MEDIA_PROCESS_CPU_TIME_LIMIT_SECONDS = int(
    os.environ.get(
        "MEDIA_PROCESS_CPU_TIME_LIMIT_SECONDS",
        str(DefaultSettings.MEDIA_PROCESS_CPU_TIME_LIMIT_SECONDS),
    )
)
MEDIA_PROCESS_MEMORY_LIMIT_MB = int(
    os.environ.get(
        "MEDIA_PROCESS_MEMORY_LIMIT_MB",
        str(DefaultSettings.MEDIA_PROCESS_MEMORY_LIMIT_MB),
    )
)
MEDIA_PROCESS_OUTPUT_FILE_SIZE_LIMIT_MB = int(
    os.environ.get(
        "MEDIA_PROCESS_OUTPUT_FILE_SIZE_LIMIT_MB",
        str(DefaultSettings.MEDIA_PROCESS_OUTPUT_FILE_SIZE_LIMIT_MB),
    )
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "corsheaders",
    "storages",
    "app",
    "anymail",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "videoq.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "videoq.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        os.environ.get("DATABASE_URL", DefaultSettings.DATABASE_URL)
    )
}

# Cache configuration
# USE_DATABASE_CACHE=true の場合は DatabaseCache (Aurora) を使用。
# Redis が不要になるため Lambda 環境でのコスト削減に有効。
_use_database_cache = (
    os.environ.get("USE_DATABASE_CACHE", "false").lower() == "true"
)
if _use_database_cache:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "django_cache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.environ.get("CACHE_URL", DefaultSettings.CACHE_URL),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Chicago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Always set STATIC_ROOT (required for collectstatic command)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "app.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "app.presentation.common.authentication.APIKeyAuthentication",
        "app.presentation.common.authentication.CookieJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Security: Disable Browsable API in production
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "app.presentation.common.exceptions.custom_exception_handler",
    # Rate limiting: accurate client IP behind reverse proxies
    "NUM_PROXIES": int(os.environ.get("NUM_PROXIES", "1")),
    "DEFAULT_THROTTLE_RATES": {
        "chat_share_token_ip": "100/hour",
        "chat_share_token_global": "1000/hour",
        "chat_authenticated": "300/hour",
        "login_ip": "5/minute",
        "login_username": "5/minute",
        "signup_ip": "3/hour",
        "signup_email": "3/hour",
        "password_reset_ip": "3/hour",
        "password_reset_email": "3/hour",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "VideoQ API",
    "DESCRIPTION": "API documentation for VideoQ application",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "AUTHENTICATION_WHITELIST": [
        "app.presentation.common.authentication.APIKeyAuthentication",
        "app.presentation.common.authentication.CookieJWTAuthentication",
    ],
    "SCHEMA_PATH_PREFIX": "/api/",
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
    ],
}

_cors_allowed_origins_env = os.environ.get("CORS_ALLOWED_ORIGINS")
if _cors_allowed_origins_env:
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in _cors_allowed_origins_env.split(",")
        if origin.strip()
    ]
else:
    CORS_ALLOWED_ORIGINS = DefaultSettings.CORS_ALLOWED_ORIGINS

# CORS: Allow credentials (required for HttpOnly Cookie authentication across origins)
CORS_ALLOW_CREDENTIALS = True

# Celery Configuration
CELERY_BROKER_URL = os.environ.get(
    "CELERY_BROKER_URL", DefaultSettings.CELERY_BROKER_URL
)
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND", DefaultSettings.CELERY_RESULT_BACKEND
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "America/Chicago"
CELERY_TASK_TRACK_STARTED = True
# Lambda 環境では CELERY_TASK_TIME_LIMIT を 840s (14 分) に設定する。
# (Lambda 最大タイムアウト 900s より短くしないとタスクが強制終了される)
CELERY_TASK_TIME_LIMIT = int(
    os.environ.get("CELERY_TASK_TIME_LIMIT", str(30 * 60))
)
CELERY_TASK_SOFT_TIME_LIMIT = int(
    os.environ.get("CELERY_TASK_SOFT_TIME_LIMIT", str(25 * 60))
)

# SQS ブローカー固有設定 (CELERY_BROKER_URL=sqs:// のときのみ有効)
if CELERY_BROKER_URL.startswith("sqs://"):
    _sqs_queue_name = os.environ.get("SQS_QUEUE_NAME", "videoq-worker")
    CELERY_TASK_DEFAULT_QUEUE = _sqs_queue_name
    CELERY_BROKER_TRANSPORT_OPTIONS = {
        "region": os.environ.get("AWS_DEFAULT_REGION", "ap-northeast-1"),
        "predefined_queues": {
            _sqs_queue_name: {
                "url": os.environ.get("SQS_QUEUE_URL", ""),
            }
        },
        # visibility_timeout は Lambda タイムアウト以上に設定すること
        "visibility_timeout": int(
            os.environ.get("CELERY_TASK_TIME_LIMIT", "840")
        ) + 60,
    }
    # SQS 環境ではリザルトバックエンド不要 (タスクは DB の状態を直接更新)
    CELERY_RESULT_BACKEND = None

# Feature flags
ENABLE_SIGNUP = os.environ.get("ENABLE_SIGNUP", "true").lower() == "true"

# Security profile: enforce secure defaults for production deployments.

SECURE_COOKIES = IS_PRODUCTION
# Lambda + API Gateway 環境では API Gateway が TLS 終端するため、
# ヘルスチェック (LWA 内部 HTTP) がリダイレクトされないよう除外する。
SECURE_SSL_REDIRECT = IS_PRODUCTION
SECURE_REDIRECT_EXEMPT = [r"^api/health/$"]
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https") if IS_PRODUCTION else None
)
SECURE_HSTS_SECONDS = 31536000 if IS_PRODUCTION else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION
SECURE_HSTS_PRELOAD = IS_PRODUCTION

# Session Cookie settings for cross-origin deployment
# When frontend and backend are on different origins, SameSite must be 'None' and Secure must be True
SESSION_COOKIE_SAMESITE = "None" if SECURE_COOKIES else "Lax"
SESSION_COOKIE_SECURE = SECURE_COOKIES
SESSION_COOKIE_HTTPONLY = True  # Prevent XSS attacks

# CSRF Cookie settings for cross-origin deployment
CSRF_COOKIE_SAMESITE = "None" if SECURE_COOKIES else "Lax"
CSRF_COOKIE_SECURE = SECURE_COOKIES
CSRF_COOKIE_HTTPONLY = False  # JavaScript needs to read CSRF token

# CSRF trusted origins (required for cross-origin POST requests)
# Use same origins as CORS_ALLOWED_ORIGINS
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# Storage configuration
USE_S3_STORAGE = (
    os.environ.get("USE_S3_STORAGE", str(DefaultSettings.USE_S3_STORAGE)).lower()
    == "true"
)

if USE_S3_STORAGE:
    # AWS S3 / Cloudflare R2 basic settings
    # On Lambda, AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY env vars are the
    # IAM role's temporary credentials — NOT the R2 API token we need for
    # django-storages.  Read R2 credentials from the app secret first
    # (populated from Secrets Manager) to avoid the collision.
    AWS_ACCESS_KEY_ID = (
        _app_secrets.get("AWS_ACCESS_KEY_ID")
        or os.environ.get("AWS_ACCESS_KEY_ID")
    )
    AWS_SECRET_ACCESS_KEY = (
        _app_secrets.get("AWS_SECRET_ACCESS_KEY")
        or os.environ.get("AWS_SECRET_ACCESS_KEY")
    )
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME") or None
    AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL") or None
    AWS_S3_CUSTOM_DOMAIN = os.environ.get("AWS_S3_CUSTOM_DOMAIN") or None

    # Presigned URL settings
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600
    AWS_S3_SIGNATURE_VERSION = "s3v4"

    # Pass R2 credentials explicitly via OPTIONS so django-storages never
    # falls back to boto3's credential chain (which picks up the Lambda IAM
    # role and adds X-Amz-Security-Token that R2 does not understand).
    # security_token=None is set via OPTIONS so hasattr() is True and
    # django-storages skips the env-var fallback in get_default_settings().
    # botocore checks "token is not None" so None means the parameter is
    # omitted entirely from presigned URLs.
    _storage_credentials = {"security_token": None}
    if AWS_ACCESS_KEY_ID:
        _storage_credentials["access_key"] = AWS_ACCESS_KEY_ID
    if AWS_SECRET_ACCESS_KEY:
        _storage_credentials["secret_key"] = AWS_SECRET_ACCESS_KEY

    # Configure storage using Django 4.2+ method
    STORAGES = {
        "staticfiles": {  # Static file storage
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                **_storage_credentials,
                "location": "static",
                "default_acl": "private",
                "object_parameters": {"CacheControl": "max-age=86400"},
            },
        },
        "default": {  # Media file storage
            "BACKEND": "app.infrastructure.models.storage.SafeS3Boto3Storage",
            "OPTIONS": {
                **_storage_credentials,
                "location": "media",
                "default_acl": "private",
                "file_overwrite": False,
            },
        },
    }
else:
    # Local development settings
    STATIC_URL = "/api/static/"
    STATIC_ROOT = BASE_DIR / "staticfiles"
    MEDIA_URL = "/api/media/"
    MEDIA_ROOT = BASE_DIR / "media"

    # Use custom storage for media files (with timestamp-based filename conversion)
    STORAGES = {
        "default": {
            "BACKEND": "app.infrastructure.models.storage.SafeFileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

FRONTEND_URL = os.environ.get("FRONTEND_URL", DefaultSettings.FRONTEND_URL)
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", DefaultSettings.DEFAULT_FROM_EMAIL
)
EMAIL_BACKEND = DefaultSettings.EMAIL_BACKEND

USE_MAILGUN = os.environ.get("USE_MAILGUN", "false").lower() == "true"

if USE_MAILGUN:
    EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
    mailgun_sender_domain = os.environ.get("MAILGUN_SENDER_DOMAIN", "")
    ANYMAIL = {
        "MAILGUN_API_KEY": os.environ.get("MAILGUN_API_KEY"),
        "MAILGUN_SENDER_DOMAIN": mailgun_sender_domain,
    }
    if "DEFAULT_FROM_EMAIL" not in os.environ and mailgun_sender_domain:
        DEFAULT_FROM_EMAIL = f"VideoQ <noreply@{mailgun_sender_domain}>"
else:
    EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", DefaultSettings.EMAIL_BACKEND)
    EMAIL_HOST = os.environ.get("EMAIL_HOST", DefaultSettings.EMAIL_HOST)
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", DefaultSettings.EMAIL_PORT))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", DefaultSettings.EMAIL_HOST_USER)
    EMAIL_HOST_PASSWORD = os.environ.get(
        "EMAIL_HOST_PASSWORD", DefaultSettings.EMAIL_HOST_PASSWORD
    )
    EMAIL_USE_TLS = (
        os.environ.get("EMAIL_USE_TLS", str(DefaultSettings.EMAIL_USE_TLS)).lower()
        == "true"
    )

# Embedding configuration
EMBEDDING_PROVIDER = os.environ.get(
    "EMBEDDING_PROVIDER", DefaultSettings.EMBEDDING_PROVIDER
).lower()
EMBEDDING_MODEL = os.environ.get("EMBEDDING_MODEL", DefaultSettings.EMBEDDING_MODEL)
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", DefaultSettings.OLLAMA_BASE_URL)

# Vector store configuration
PGVECTOR_COLLECTION_NAME = os.environ.get("PGVECTOR_COLLECTION_NAME", "videoq_scenes")

EMBEDDING_VECTOR_SIZE = int(os.environ.get("EMBEDDING_VECTOR_SIZE", 1536))

# LLM configuration
LLM_PROVIDER = os.environ.get("LLM_PROVIDER", DefaultSettings.LLM_PROVIDER).lower()
LLM_MODEL = os.environ.get("LLM_MODEL", DefaultSettings.LLM_MODEL)

# Whisper configuration
WHISPER_BACKEND = os.environ.get("WHISPER_BACKEND", DefaultSettings.WHISPER_BACKEND).lower()
