-- Baseline DDL introspected from local Postgres (Django-era schema).
-- Greenfield: applied by drizzle-kit migrate.
-- Existing DBs: stamped via scripts/stamp-baseline.mjs then skipped.

CREATE EXTENSION IF NOT EXISTS vector;
--> statement-breakpoint
CREATE TABLE "django_migrations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_migrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"app" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"applied" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "django_content_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_content_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"app_label" varchar(100) NOT NULL,
	"model" varchar(100) NOT NULL,
	CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE("app_label","model")
);
--> statement-breakpoint
CREATE TABLE "auth_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"content_type_id" integer NOT NULL,
	"codename" varchar(100) NOT NULL,
	CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE("content_type_id","codename")
);
--> statement-breakpoint
CREATE TABLE "auth_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(150) NOT NULL,
	CONSTRAINT "auth_group_name_key" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "auth_group_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_id" integer NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE("group_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "app_user_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_user_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"group_id" integer NOT NULL,
	CONSTRAINT "app_user_groups_user_id_group_id_73b8e940_uniq" UNIQUE("user_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "app_user_user_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_user_user_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "app_user_user_permissions_user_id_permission_id_7c8316ce_uniq" UNIQUE("user_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "app_videogroupmember" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_videogroupmember_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"added_at" timestamp with time zone NOT NULL,
	"order" integer NOT NULL,
	"group_id" bigint NOT NULL,
	"video_id" bigint NOT NULL,
	CONSTRAINT "app_videogroupmember_group_id_video_id_6ac1be60_uniq" UNIQUE("group_id","video_id")
);
--> statement-breakpoint
CREATE TABLE "django_admin_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_admin_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action_time" timestamp with time zone NOT NULL,
	"object_id" text,
	"object_repr" varchar(200) NOT NULL,
	"action_flag" smallint NOT NULL,
	"change_message" text NOT NULL,
	"content_type_id" integer,
	"user_id" bigint NOT NULL,
	CONSTRAINT "django_admin_log_action_flag_check" CHECK (action_flag >= 0)
);
--> statement-breakpoint
CREATE TABLE "app_video" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_video_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"file" varchar(100) NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"uploaded_at" timestamp with time zone NOT NULL,
	"transcript" text NOT NULL,
	"status" varchar(20) NOT NULL,
	"error_message" text NOT NULL,
	"user_id" bigint NOT NULL,
	"source_type" varchar(20) NOT NULL,
	"source_url" varchar(200) NOT NULL,
	"youtube_video_id" varchar(32) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_chatlog" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_chatlog_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"question" text NOT NULL,
	"answer" text NOT NULL,
	"citations" jsonb NOT NULL,
	"is_shared_origin" boolean NOT NULL,
	"feedback" varchar(4),
	"created_at" timestamp with time zone NOT NULL,
	"user_id" bigint NOT NULL,
	"group_id" bigint NOT NULL,
	"retrieved_contexts" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_videogroup" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_videogroup_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"user_id" bigint NOT NULL,
	"share_slug" varchar(64),
	"display_order" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_tag" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"color" varchar(20) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "app_tag_user_id_name_4d8bb7f5_uniq" UNIQUE("name","user_id")
);
--> statement-breakpoint
CREATE TABLE "app_videotag" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_videotag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"added_at" timestamp with time zone NOT NULL,
	"tag_id" bigint NOT NULL,
	"video_id" bigint NOT NULL,
	CONSTRAINT "app_videotag_video_id_tag_id_dc926f33_uniq" UNIQUE("tag_id","video_id")
);
--> statement-breakpoint
CREATE TABLE "django_session" (
	"session_key" varchar(40) PRIMARY KEY NOT NULL,
	"session_data" text NOT NULL,
	"expire_date" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_accountdeletionrequest" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_accountdeletionrequest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reason" text NOT NULL,
	"requested_at" timestamp with time zone NOT NULL,
	"user_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "videoq_scenes" (
	"langchain_id" uuid PRIMARY KEY NOT NULL,
	"content" text NOT NULL,
	"embedding" vector(1024) NOT NULL,
	"user_id" integer,
	"video_id" integer,
	"langchain_metadata" json
);
--> statement-breakpoint
CREATE TABLE "app_userapikey" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_userapikey_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"prefix" varchar(12) NOT NULL,
	"hashed_key" varchar(64) NOT NULL,
	"last_used_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"user_id" bigint NOT NULL,
	"access_level" varchar(20) NOT NULL,
	CONSTRAINT "app_userapikey_hashed_key_key" UNIQUE("hashed_key")
);
--> statement-breakpoint
CREATE TABLE "django_cache" (
	"cache_key" varchar(255) PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_document" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_document_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"file" varchar(100) NOT NULL,
	"md_tree" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"user_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_documentgroupmember" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_documentgroupmember_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"added_at" timestamp with time zone NOT NULL,
	"order" integer NOT NULL,
	"document_id" bigint NOT NULL,
	"group_id" bigint NOT NULL,
	CONSTRAINT "app_documentgroupmember_group_id_document_id_86648044_uniq" UNIQUE("document_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "app_documenttag" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_documenttag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"added_at" timestamp with time zone NOT NULL,
	"document_id" bigint NOT NULL,
	"tag_id" bigint NOT NULL,
	CONSTRAINT "app_documenttag_document_id_tag_id_866b55f0_uniq" UNIQUE("document_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE "app_groupevaluationsnapshot" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_groupevaluationsnapshot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sample_count" integer NOT NULL,
	"faithfulness_mean" double precision,
	"answer_relevancy_mean" double precision,
	"samples" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"group_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"context_precision_mean" double precision,
	CONSTRAINT "app_groupevaluationsnapshot_group_id_key" UNIQUE("group_id")
);
--> statement-breakpoint
CREATE TABLE "app_chatlogevaluation" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_chatlogevaluation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"status" varchar(20) NOT NULL,
	"faithfulness" double precision,
	"answer_relevancy" double precision,
	"context_precision" double precision,
	"error_message" text NOT NULL,
	"evaluated_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"chat_log_id" bigint NOT NULL,
	CONSTRAINT "app_chatlogevaluation_chat_log_id_key" UNIQUE("chat_log_id")
);
--> statement-breakpoint
CREATE TABLE "app_user" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"password" varchar(128) NOT NULL,
	"last_login" timestamp with time zone,
	"is_superuser" boolean NOT NULL,
	"username" varchar(150) NOT NULL,
	"first_name" varchar(150) NOT NULL,
	"last_name" varchar(150) NOT NULL,
	"is_staff" boolean NOT NULL,
	"is_active" boolean NOT NULL,
	"date_joined" timestamp with time zone NOT NULL,
	"email" varchar(254) NOT NULL,
	"deactivated_at" timestamp with time zone,
	"max_video_upload_size_mb" integer NOT NULL,
	"searchapi_api_key_encrypted" "bytea",
	"ai_answers_limit" integer,
	"is_over_quota" boolean NOT NULL,
	"processing_limit_minutes" integer,
	"storage_limit_gb" double precision,
	"usage_period_start" timestamp with time zone,
	"used_ai_answers" integer NOT NULL,
	"used_processing_seconds" integer NOT NULL,
	"used_storage_bytes" bigint NOT NULL,
	"pending_email" varchar(254),
	CONSTRAINT "app_user_username_key" UNIQUE("username"),
	CONSTRAINT "app_user_email_key" UNIQUE("email"),
	CONSTRAINT "app_user_max_video_upload_size_mb_check" CHECK (max_video_upload_size_mb >= 0)
);
--> statement-breakpoint
CREATE TABLE "oauth2_provider_accesstoken" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth2_provider_accesstoken_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token" text NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	"scope" text NOT NULL,
	"application_id" bigint,
	"user_id" bigint,
	"created" timestamp with time zone NOT NULL,
	"updated" timestamp with time zone NOT NULL,
	"source_refresh_token_id" bigint,
	"id_token_id" bigint,
	"token_checksum" varchar(64) NOT NULL,
	CONSTRAINT "oauth2_provider_accesstoken_source_refresh_token_id_key" UNIQUE("source_refresh_token_id"),
	CONSTRAINT "oauth2_provider_accesstoken_id_token_id_key" UNIQUE("id_token_id"),
	CONSTRAINT "oauth2_provider_accesstoken_token_checksum_85319a26_uniq" UNIQUE("token_checksum")
);
--> statement-breakpoint
CREATE TABLE "oauth2_provider_idtoken" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth2_provider_idtoken_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"jti" uuid NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	"scope" text NOT NULL,
	"created" timestamp with time zone NOT NULL,
	"updated" timestamp with time zone NOT NULL,
	"application_id" bigint,
	"user_id" bigint,
	CONSTRAINT "oauth2_provider_idtoken_jti_key" UNIQUE("jti")
);
--> statement-breakpoint
CREATE TABLE "oauth2_provider_grant" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth2_provider_grant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	"redirect_uri" text NOT NULL,
	"scope" text NOT NULL,
	"application_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"created" timestamp with time zone NOT NULL,
	"updated" timestamp with time zone NOT NULL,
	"code_challenge" varchar(128) NOT NULL,
	"code_challenge_method" varchar(10) NOT NULL,
	"nonce" varchar(255) NOT NULL,
	"claims" text NOT NULL,
	CONSTRAINT "oauth2_provider_grant_code_key" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "oauth2_provider_devicegrant" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth2_provider_devicegrant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"device_code" varchar(100) NOT NULL,
	"user_code" varchar(100) NOT NULL,
	"scope" varchar(64),
	"interval" integer NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	"status" varchar(64) NOT NULL,
	"client_id" varchar(100) NOT NULL,
	"last_checked" timestamp with time zone NOT NULL,
	"user_id" bigint,
	CONSTRAINT "oauth2_provider_devicegrant_unique_device_code" UNIQUE("device_code")
);
--> statement-breakpoint
CREATE TABLE "oauth2_provider_application" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth2_provider_application_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_id" varchar(100) NOT NULL,
	"redirect_uris" text NOT NULL,
	"client_type" varchar(32) NOT NULL,
	"authorization_grant_type" varchar(44) NOT NULL,
	"client_secret" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"user_id" bigint,
	"skip_authorization" boolean NOT NULL,
	"created" timestamp with time zone NOT NULL,
	"updated" timestamp with time zone NOT NULL,
	"algorithm" varchar(5) NOT NULL,
	"post_logout_redirect_uris" text NOT NULL,
	"hash_client_secret" boolean NOT NULL,
	"allowed_origins" text NOT NULL,
	CONSTRAINT "oauth2_provider_application_client_id_key" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE "oauth2_provider_refreshtoken" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth2_provider_refreshtoken_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token" varchar(255) NOT NULL,
	"access_token_id" bigint,
	"application_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"created" timestamp with time zone NOT NULL,
	"updated" timestamp with time zone NOT NULL,
	"revoked" timestamp with time zone,
	"token_family" uuid,
	CONSTRAINT "oauth2_provider_refreshtoken_token_revoked_af8a5134_uniq" UNIQUE("token","revoked"),
	CONSTRAINT "oauth2_provider_refreshtoken_access_token_id_key" UNIQUE("access_token_id")
);
--> statement-breakpoint
CREATE TABLE "app_plogbuildjob" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_plogbuildjob_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"status" varchar(20) NOT NULL,
	"error_message" text NOT NULL,
	"input_tokens" integer NOT NULL,
	"output_tokens" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone,
	"video_id" bigint NOT NULL,
	CONSTRAINT "app_plogbuildjob_input_tokens_check" CHECK (input_tokens >= 0),
	CONSTRAINT "app_plogbuildjob_output_tokens_check" CHECK (output_tokens >= 0)
);
--> statement-breakpoint
CREATE TABLE "app_plogsummarynode" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_plogsummarynode_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"level" smallint NOT NULL,
	"text" text NOT NULL,
	"start_sec" double precision NOT NULL,
	"end_sec" double precision NOT NULL,
	"scene_indices" jsonb NOT NULL,
	"embedding" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"parent_id" bigint,
	"video_id" bigint NOT NULL,
	CONSTRAINT "app_plogsummarynode_level_check" CHECK (level >= 0)
);
--> statement-breakpoint
CREATE TABLE "app_plogconcept" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_plogconcept_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"label" varchar(255) NOT NULL,
	"node_type" varchar(20) NOT NULL,
	"intro_sec" double precision NOT NULL,
	"source_quote" text NOT NULL,
	"embedding" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"video_id" bigint NOT NULL,
	CONSTRAINT "plog_concept_unique_label_per_video" UNIQUE("label","video_id")
);
--> statement-breakpoint
CREATE TABLE "app_plogedge" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_plogedge_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"edge_type" varchar(32) NOT NULL,
	"quote" text NOT NULL,
	"validation_status" varchar(20) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"source_id" bigint NOT NULL,
	"target_id" bigint NOT NULL,
	"video_id" bigint NOT NULL,
	CONSTRAINT "plog_edge_unique_typed_pair" UNIQUE("edge_type","source_id","target_id","video_id")
);
--> statement-breakpoint
CREATE TABLE "app_ploglearningobject" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_ploglearningobject_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"opening_question" text NOT NULL,
	"hint_ladder" jsonb NOT NULL,
	"misconceptions" jsonb NOT NULL,
	"canonical_order" jsonb NOT NULL,
	"worked_examples" jsonb NOT NULL,
	"waypoints" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"concept_id" bigint NOT NULL,
	CONSTRAINT "app_ploglearningobject_concept_id_key" UNIQUE("concept_id")
);
--> statement-breakpoint
CREATE TABLE "app_learnerconceptstate" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_learnerconceptstate_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reached" boolean NOT NULL,
	"hint_index" smallint NOT NULL,
	"last_grade" varchar(32) NOT NULL,
	"active" boolean NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"concept_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "learner_concept_state_unique" UNIQUE("concept_id","user_id"),
	CONSTRAINT "app_learnerconceptstate_hint_index_check" CHECK (hint_index >= 0)
);
--> statement-breakpoint
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_groups" ADD CONSTRAINT "app_user_groups_user_id_e6f878f6_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_groups" ADD CONSTRAINT "app_user_groups_group_id_e774d92c_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_user_permissions" ADD CONSTRAINT "app_user_user_permissions_user_id_24780b52_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_user_permissions" ADD CONSTRAINT "app_user_user_permis_permission_id_4ef8e133_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_videogroupmember" ADD CONSTRAINT "app_videogroupmember_group_id_49a71957_fk_app_videogroup_id" FOREIGN KEY ("group_id") REFERENCES "public"."app_videogroup"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_videogroupmember" ADD CONSTRAINT "app_videogroupmember_video_id_80f96834_fk_app_video_id" FOREIGN KEY ("video_id") REFERENCES "public"."app_video"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_video" ADD CONSTRAINT "app_video_user_id_3ed4447b_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_chatlog" ADD CONSTRAINT "app_chatlog_user_id_15b02103_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_chatlog" ADD CONSTRAINT "app_chatlog_group_id_89e804ad_fk_app_videogroup_id" FOREIGN KEY ("group_id") REFERENCES "public"."app_videogroup"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_videogroup" ADD CONSTRAINT "app_videogroup_user_id_14cb0044_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_tag" ADD CONSTRAINT "app_tag_user_id_3eb7ac2a_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_videotag" ADD CONSTRAINT "app_videotag_tag_id_ea4fed1c_fk_app_tag_id" FOREIGN KEY ("tag_id") REFERENCES "public"."app_tag"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_videotag" ADD CONSTRAINT "app_videotag_video_id_fbe1bc77_fk_app_video_id" FOREIGN KEY ("video_id") REFERENCES "public"."app_video"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_accountdeletionrequest" ADD CONSTRAINT "app_accountdeletionrequest_user_id_d8be8ff6_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_userapikey" ADD CONSTRAINT "app_userapikey_user_id_fe6b52b7_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_document" ADD CONSTRAINT "app_document_user_id_ea8b83b8_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_documentgroupmember" ADD CONSTRAINT "app_documentgroupmember_document_id_250b9944_fk_app_document_id" FOREIGN KEY ("document_id") REFERENCES "public"."app_document"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_documentgroupmember" ADD CONSTRAINT "app_documentgroupmember_group_id_51c58381_fk_app_videogroup_id" FOREIGN KEY ("group_id") REFERENCES "public"."app_videogroup"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_documenttag" ADD CONSTRAINT "app_documenttag_document_id_dcf38c9e_fk_app_document_id" FOREIGN KEY ("document_id") REFERENCES "public"."app_document"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_documenttag" ADD CONSTRAINT "app_documenttag_tag_id_cbe22395_fk_app_tag_id" FOREIGN KEY ("tag_id") REFERENCES "public"."app_tag"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_groupevaluationsnapshot" ADD CONSTRAINT "app_groupevaluations_group_id_7bbb01cf_fk_app_video" FOREIGN KEY ("group_id") REFERENCES "public"."app_videogroup"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_groupevaluationsnapshot" ADD CONSTRAINT "app_groupevaluationsnapshot_user_id_e206b1f1_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_chatlogevaluation" ADD CONSTRAINT "app_chatlogevaluation_chat_log_id_a64c4808_fk_app_chatlog_id" FOREIGN KEY ("chat_log_id") REFERENCES "public"."app_chatlog"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_accesstoken" ADD CONSTRAINT "oauth2_provider_acce_source_refresh_token_e66fbc72_fk_oauth2_pr" FOREIGN KEY ("source_refresh_token_id") REFERENCES "public"."oauth2_provider_refreshtoken"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_accesstoken" ADD CONSTRAINT "oauth2_provider_acce_application_id_b22886e1_fk_oauth2_pr" FOREIGN KEY ("application_id") REFERENCES "public"."oauth2_provider_application"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_accesstoken" ADD CONSTRAINT "oauth2_provider_accesstoken_user_id_6e4c9a65_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_accesstoken" ADD CONSTRAINT "oauth2_provider_acce_id_token_id_85db651b_fk_oauth2_pr" FOREIGN KEY ("id_token_id") REFERENCES "public"."oauth2_provider_idtoken"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_idtoken" ADD CONSTRAINT "oauth2_provider_idto_application_id_08c5ff4f_fk_oauth2_pr" FOREIGN KEY ("application_id") REFERENCES "public"."oauth2_provider_application"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_idtoken" ADD CONSTRAINT "oauth2_provider_idtoken_user_id_dd512b59_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_grant" ADD CONSTRAINT "oauth2_provider_gran_application_id_81923564_fk_oauth2_pr" FOREIGN KEY ("application_id") REFERENCES "public"."oauth2_provider_application"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_grant" ADD CONSTRAINT "oauth2_provider_grant_user_id_e8f62af8_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_devicegrant" ADD CONSTRAINT "oauth2_provider_devicegrant_user_id_1cec5156_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_application" ADD CONSTRAINT "oauth2_provider_application_user_id_79829054_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_refreshtoken" ADD CONSTRAINT "oauth2_provider_refr_access_token_id_775e84e8_fk_oauth2_pr" FOREIGN KEY ("access_token_id") REFERENCES "public"."oauth2_provider_accesstoken"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_refreshtoken" ADD CONSTRAINT "oauth2_provider_refr_application_id_2d1c311b_fk_oauth2_pr" FOREIGN KEY ("application_id") REFERENCES "public"."oauth2_provider_application"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth2_provider_refreshtoken" ADD CONSTRAINT "oauth2_provider_refreshtoken_user_id_da837fce_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_plogbuildjob" ADD CONSTRAINT "app_plogbuildjob_video_id_e75c897e_fk_app_video_id" FOREIGN KEY ("video_id") REFERENCES "public"."app_video"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_plogsummarynode" ADD CONSTRAINT "app_plogsummarynode_parent_id_e7b13c0a_fk_app_plogs" FOREIGN KEY ("parent_id") REFERENCES "public"."app_plogsummarynode"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_plogsummarynode" ADD CONSTRAINT "app_plogsummarynode_video_id_9bcf5b47_fk_app_video_id" FOREIGN KEY ("video_id") REFERENCES "public"."app_video"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_plogconcept" ADD CONSTRAINT "app_plogconcept_video_id_81b10353_fk_app_video_id" FOREIGN KEY ("video_id") REFERENCES "public"."app_video"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_plogedge" ADD CONSTRAINT "app_plogedge_source_id_2e1ccbe2_fk_app_plogconcept_id" FOREIGN KEY ("source_id") REFERENCES "public"."app_plogconcept"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_plogedge" ADD CONSTRAINT "app_plogedge_target_id_0b853bc8_fk_app_plogconcept_id" FOREIGN KEY ("target_id") REFERENCES "public"."app_plogconcept"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_plogedge" ADD CONSTRAINT "app_plogedge_video_id_c0d24124_fk_app_video_id" FOREIGN KEY ("video_id") REFERENCES "public"."app_video"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_ploglearningobject" ADD CONSTRAINT "app_ploglearningobje_concept_id_77171d07_fk_app_plogc" FOREIGN KEY ("concept_id") REFERENCES "public"."app_plogconcept"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_learnerconceptstate" ADD CONSTRAINT "app_learnerconceptst_concept_id_e626a63f_fk_app_plogc" FOREIGN KEY ("concept_id") REFERENCES "public"."app_plogconcept"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_learnerconceptstate" ADD CONSTRAINT "app_learnerconceptstate_user_id_640b1dc5_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" USING btree ("content_type_id");--> statement-breakpoint
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" USING btree ("name");--> statement-breakpoint
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" USING btree ("permission_id");--> statement-breakpoint
CREATE INDEX "app_user_groups_group_id_e774d92c" ON "app_user_groups" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "app_user_groups_user_id_e6f878f6" ON "app_user_groups" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_user_user_permissions_permission_id_4ef8e133" ON "app_user_user_permissions" USING btree ("permission_id");--> statement-breakpoint
CREATE INDEX "app_user_user_permissions_user_id_24780b52" ON "app_user_user_permissions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_videogr_group_i_d0eb57_idx" ON "app_videogroupmember" USING btree ("group_id","order");--> statement-breakpoint
CREATE INDEX "app_videogr_video_i_f96db2_idx" ON "app_videogroupmember" USING btree ("video_id","group_id");--> statement-breakpoint
CREATE INDEX "app_videogroupmember_added_at_8cb55549" ON "app_videogroupmember" USING btree ("added_at");--> statement-breakpoint
CREATE INDEX "app_videogroupmember_group_id_49a71957" ON "app_videogroupmember" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "app_videogroupmember_order_45f29711" ON "app_videogroupmember" USING btree ("order");--> statement-breakpoint
CREATE INDEX "app_videogroupmember_video_id_80f96834" ON "app_videogroupmember" USING btree ("video_id");--> statement-breakpoint
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" USING btree ("content_type_id");--> statement-breakpoint
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_video_source_type_505add14" ON "app_video" USING btree ("source_type");--> statement-breakpoint
CREATE INDEX "app_video_source_type_505add14_like" ON "app_video" USING btree ("source_type");--> statement-breakpoint
CREATE INDEX "app_video_status_d35a7171" ON "app_video" USING btree ("status");--> statement-breakpoint
CREATE INDEX "app_video_status_d35a7171_like" ON "app_video" USING btree ("status");--> statement-breakpoint
CREATE INDEX "app_video_uploaded_at_39d6770e" ON "app_video" USING btree ("uploaded_at");--> statement-breakpoint
CREATE INDEX "app_video_user_id_3ed4447b" ON "app_video" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_video_user_id_9c7398_idx" ON "app_video" USING btree ("user_id","status","uploaded_at");--> statement-breakpoint
CREATE INDEX "app_video_user_id_d60748_idx" ON "app_video" USING btree ("user_id","title");--> statement-breakpoint
CREATE INDEX "app_video_user_id_de5bbd_idx" ON "app_video" USING btree ("user_id","source_type","uploaded_at");--> statement-breakpoint
CREATE INDEX "app_video_youtube_video_id_30ca5041" ON "app_video" USING btree ("youtube_video_id");--> statement-breakpoint
CREATE INDEX "app_video_youtube_video_id_30ca5041_like" ON "app_video" USING btree ("youtube_video_id");--> statement-breakpoint
CREATE INDEX "app_chatlog_created_at_f6c528b1" ON "app_chatlog" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "app_chatlog_feedback_2b075392" ON "app_chatlog" USING btree ("feedback");--> statement-breakpoint
CREATE INDEX "app_chatlog_feedback_2b075392_like" ON "app_chatlog" USING btree ("feedback");--> statement-breakpoint
CREATE INDEX "app_chatlog_group_i_4bc6d0_idx" ON "app_chatlog" USING btree ("group_id","created_at");--> statement-breakpoint
CREATE INDEX "app_chatlog_group_id_89e804ad" ON "app_chatlog" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "app_chatlog_is_shared_origin_4c3d7c4b" ON "app_chatlog" USING btree ("is_shared_origin");--> statement-breakpoint
CREATE INDEX "app_chatlog_user_id_15b02103" ON "app_chatlog" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_chatlog_user_id_727742_idx" ON "app_chatlog" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "chatlog_feedback_idx" ON "app_chatlog" USING btree ("feedback") WHERE (feedback IS NOT NULL);--> statement-breakpoint
CREATE INDEX "app_videogr_user_id_dd31d1_idx" ON "app_videogroup" USING btree ("user_id","display_order","created_at");--> statement-breakpoint
CREATE INDEX "app_videogroup_created_at_ac4989dd" ON "app_videogroup" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "app_videogroup_display_order_e3a863be" ON "app_videogroup" USING btree ("display_order");--> statement-breakpoint
CREATE INDEX "app_videogroup_share_slug_4c4c8350" ON "app_videogroup" USING btree ("share_slug");--> statement-breakpoint
CREATE INDEX "app_videogroup_share_slug_4c4c8350_like" ON "app_videogroup" USING btree ("share_slug");--> statement-breakpoint
CREATE INDEX "app_videogroup_user_id_14cb0044" ON "app_videogroup" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "videogroup_share_slug_ci_uniq" ON "app_videogroup" USING btree (lower((share_slug)::text)) WHERE (share_slug IS NOT NULL);--> statement-breakpoint
CREATE INDEX "videogroup_share_slug_idx" ON "app_videogroup" USING btree ("share_slug") WHERE (share_slug IS NOT NULL);--> statement-breakpoint
CREATE INDEX "app_tag_created_at_d1ea9b01" ON "app_tag" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "app_tag_name_749da597" ON "app_tag" USING btree ("name");--> statement-breakpoint
CREATE INDEX "app_tag_name_749da597_like" ON "app_tag" USING btree ("name");--> statement-breakpoint
CREATE INDEX "app_tag_user_id_3eb7ac2a" ON "app_tag" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_tag_user_id_b053bd_idx" ON "app_tag" USING btree ("user_id","name");--> statement-breakpoint
CREATE INDEX "app_videota_tag_id_94f309_idx" ON "app_videotag" USING btree ("tag_id","added_at");--> statement-breakpoint
CREATE INDEX "app_videota_video_i_3d974b_idx" ON "app_videotag" USING btree ("video_id","tag_id");--> statement-breakpoint
CREATE INDEX "app_videotag_added_at_aadce5c2" ON "app_videotag" USING btree ("added_at");--> statement-breakpoint
CREATE INDEX "app_videotag_tag_id_ea4fed1c" ON "app_videotag" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "app_videotag_video_id_fbe1bc77" ON "app_videotag" USING btree ("video_id");--> statement-breakpoint
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" USING btree ("expire_date");--> statement-breakpoint
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" USING btree ("session_key");--> statement-breakpoint
CREATE INDEX "app_account_user_id_8f2281_idx" ON "app_accountdeletionrequest" USING btree ("user_id","requested_at");--> statement-breakpoint
CREATE INDEX "app_accountdeletionrequest_requested_at_1b2b1cad" ON "app_accountdeletionrequest" USING btree ("requested_at");--> statement-breakpoint
CREATE INDEX "app_accountdeletionrequest_user_id_d8be8ff6" ON "app_accountdeletionrequest" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_userapikey_hashed_key_ef4433cf_like" ON "app_userapikey" USING btree ("hashed_key");--> statement-breakpoint
CREATE INDEX "app_userapikey_prefix_e83c0375" ON "app_userapikey" USING btree ("prefix");--> statement-breakpoint
CREATE INDEX "app_userapikey_prefix_e83c0375_like" ON "app_userapikey" USING btree ("prefix");--> statement-breakpoint
CREATE INDEX "app_userapikey_revoked_at_962cc7a2" ON "app_userapikey" USING btree ("revoked_at");--> statement-breakpoint
CREATE INDEX "app_userapikey_user_id_fe6b52b7" ON "app_userapikey" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_active_api_key_name_per_user" ON "app_userapikey" USING btree ("user_id","name") WHERE (revoked_at IS NULL);--> statement-breakpoint
CREATE INDEX "django_cache_expires_idx" ON "django_cache" USING btree ("expires");--> statement-breakpoint
CREATE INDEX "app_documen_user_id_4575e2_idx" ON "app_document" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "app_document_created_at_071869b5" ON "app_document" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "app_document_user_id_ea8b83b8" ON "app_document" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_documen_group_i_c4a377_idx" ON "app_documentgroupmember" USING btree ("group_id","order");--> statement-breakpoint
CREATE INDEX "app_documentgroupmember_added_at_ce3de8ba" ON "app_documentgroupmember" USING btree ("added_at");--> statement-breakpoint
CREATE INDEX "app_documentgroupmember_document_id_250b9944" ON "app_documentgroupmember" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "app_documentgroupmember_group_id_51c58381" ON "app_documentgroupmember" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "app_documentgroupmember_order_abddc6a9" ON "app_documentgroupmember" USING btree ("order");--> statement-breakpoint
CREATE INDEX "app_documen_documen_fde2b3_idx" ON "app_documenttag" USING btree ("document_id","tag_id");--> statement-breakpoint
CREATE INDEX "app_documen_tag_id_b66f22_idx" ON "app_documenttag" USING btree ("tag_id","added_at");--> statement-breakpoint
CREATE INDEX "app_documenttag_added_at_08d9c140" ON "app_documenttag" USING btree ("added_at");--> statement-breakpoint
CREATE INDEX "app_documenttag_document_id_dcf38c9e" ON "app_documenttag" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "app_documenttag_tag_id_cbe22395" ON "app_documenttag" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "app_groupev_user_id_e828b6_idx" ON "app_groupevaluationsnapshot" USING btree ("user_id","updated_at");--> statement-breakpoint
CREATE INDEX "app_groupevaluationsnapshot_created_at_85b64cef" ON "app_groupevaluationsnapshot" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "app_groupevaluationsnapshot_user_id_e206b1f1" ON "app_groupevaluationsnapshot" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_chatlog_status_6ea271_idx" ON "app_chatlogevaluation" USING btree ("status");--> statement-breakpoint
CREATE INDEX "app_chatlogevaluation_status_26824a3d" ON "app_chatlogevaluation" USING btree ("status");--> statement-breakpoint
CREATE INDEX "app_chatlogevaluation_status_26824a3d_like" ON "app_chatlogevaluation" USING btree ("status");--> statement-breakpoint
CREATE INDEX "app_user_date_jo_c41876_idx" ON "app_user" USING btree ("date_joined","id");--> statement-breakpoint
CREATE INDEX "app_user_deactivated_at_9b55afc1" ON "app_user" USING btree ("deactivated_at");--> statement-breakpoint
CREATE INDEX "app_user_email_a838b5_idx" ON "app_user" USING btree ("email","is_active");--> statement-breakpoint
CREATE INDEX "app_user_email_efde8896_like" ON "app_user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "app_user_pending_email_7dde5485" ON "app_user" USING btree ("pending_email");--> statement-breakpoint
CREATE INDEX "app_user_pending_email_7dde5485_like" ON "app_user" USING btree ("pending_email");--> statement-breakpoint
CREATE INDEX "app_user_username_9d6296ff_like" ON "app_user" USING btree ("username");--> statement-breakpoint
CREATE INDEX "oauth2_provider_accesstoken_application_id_b22886e1" ON "oauth2_provider_accesstoken" USING btree ("application_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_accesstoken_token_checksum_85319a26_like" ON "oauth2_provider_accesstoken" USING btree ("token_checksum");--> statement-breakpoint
CREATE INDEX "oauth2_provider_accesstoken_user_id_6e4c9a65" ON "oauth2_provider_accesstoken" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_idtoken_application_id_08c5ff4f" ON "oauth2_provider_idtoken" USING btree ("application_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_idtoken_user_id_dd512b59" ON "oauth2_provider_idtoken" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_grant_application_id_81923564" ON "oauth2_provider_grant" USING btree ("application_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_grant_code_49ab4ddf_like" ON "oauth2_provider_grant" USING btree ("code");--> statement-breakpoint
CREATE INDEX "oauth2_provider_grant_user_id_e8f62af8" ON "oauth2_provider_grant" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_devicegrant_client_id_229dd06d" ON "oauth2_provider_devicegrant" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_devicegrant_client_id_229dd06d_like" ON "oauth2_provider_devicegrant" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_devicegrant_device_code_ab91e379_like" ON "oauth2_provider_devicegrant" USING btree ("device_code");--> statement-breakpoint
CREATE INDEX "oauth2_provider_devicegrant_user_id_1cec5156" ON "oauth2_provider_devicegrant" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_application_client_id_03f0cc84_like" ON "oauth2_provider_application" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_application_client_secret_53133678" ON "oauth2_provider_application" USING btree ("client_secret");--> statement-breakpoint
CREATE INDEX "oauth2_provider_application_client_secret_53133678_like" ON "oauth2_provider_application" USING btree ("client_secret");--> statement-breakpoint
CREATE INDEX "oauth2_provider_application_user_id_79829054" ON "oauth2_provider_application" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_refreshtoken_application_id_2d1c311b" ON "oauth2_provider_refreshtoken" USING btree ("application_id");--> statement-breakpoint
CREATE INDEX "oauth2_provider_refreshtoken_user_id_da837fce" ON "oauth2_provider_refreshtoken" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_plogbui_video_i_idx" ON "app_plogbuildjob" USING btree ("video_id","created_at");--> statement-breakpoint
CREATE INDEX "app_plogbuildjob_created_at_71482637" ON "app_plogbuildjob" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "app_plogbuildjob_status_08fd6815" ON "app_plogbuildjob" USING btree ("status");--> statement-breakpoint
CREATE INDEX "app_plogbuildjob_status_08fd6815_like" ON "app_plogbuildjob" USING btree ("status");--> statement-breakpoint
CREATE INDEX "app_plogbuildjob_video_id_e75c897e" ON "app_plogbuildjob" USING btree ("video_id");--> statement-breakpoint
CREATE INDEX "app_plogsum_video_i_idx" ON "app_plogsummarynode" USING btree ("video_id","level");--> statement-breakpoint
CREATE INDEX "app_plogsummarynode_level_c5b6008a" ON "app_plogsummarynode" USING btree ("level");--> statement-breakpoint
CREATE INDEX "app_plogsummarynode_parent_id_e7b13c0a" ON "app_plogsummarynode" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "app_plogsummarynode_video_id_9bcf5b47" ON "app_plogsummarynode" USING btree ("video_id");--> statement-breakpoint
CREATE INDEX "app_plogcon_video_i_idx" ON "app_plogconcept" USING btree ("video_id","intro_sec");--> statement-breakpoint
CREATE INDEX "app_plogconcept_video_id_81b10353" ON "app_plogconcept" USING btree ("video_id");--> statement-breakpoint
CREATE INDEX "app_plogedg_video_i_idx" ON "app_plogedge" USING btree ("video_id","edge_type");--> statement-breakpoint
CREATE INDEX "app_plogedg_video_i_idx2" ON "app_plogedge" USING btree ("video_id","validation_status");--> statement-breakpoint
CREATE INDEX "app_plogedge_source_id_2e1ccbe2" ON "app_plogedge" USING btree ("source_id");--> statement-breakpoint
CREATE INDEX "app_plogedge_target_id_0b853bc8" ON "app_plogedge" USING btree ("target_id");--> statement-breakpoint
CREATE INDEX "app_plogedge_validation_status_36235281" ON "app_plogedge" USING btree ("validation_status");--> statement-breakpoint
CREATE INDEX "app_plogedge_validation_status_36235281_like" ON "app_plogedge" USING btree ("validation_status");--> statement-breakpoint
CREATE INDEX "app_plogedge_video_id_c0d24124" ON "app_plogedge" USING btree ("video_id");--> statement-breakpoint
CREATE INDEX "app_learner_user_id_idx" ON "app_learnerconceptstate" USING btree ("user_id","reached");--> statement-breakpoint
CREATE INDEX "app_learnerconceptstate_concept_id_e626a63f" ON "app_learnerconceptstate" USING btree ("concept_id");--> statement-breakpoint
CREATE INDEX "app_learnerconceptstate_reached_e0b0973c" ON "app_learnerconceptstate" USING btree ("reached");--> statement-breakpoint
CREATE INDEX "app_learnerconceptstate_user_id_640b1dc5" ON "app_learnerconceptstate" USING btree ("user_id");
