-- Modern schema (additive). Legacy app_* tables remain until post-cutover drop.
CREATE EXTENSION IF NOT EXISTS vector;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"password" varchar(128) NOT NULL,
	"last_login" timestamp with time zone,
	"is_superuser" boolean NOT NULL,
	"username" varchar(150) NOT NULL,
	"first_name" varchar(150) NOT NULL,
	"last_name" varchar(150) NOT NULL,
	"is_staff" boolean NOT NULL,
	"is_active" boolean NOT NULL,
	"date_joined" timestamp with time zone NOT NULL,
	"email" varchar(254) NOT NULL,
	"deactivated_at" timestamp with time zone,
	"max_video_upload_size_mb" integer NOT NULL,
	"searchapi_api_key_encrypted" bytea,
	"ai_answers_limit" integer,
	"is_over_quota" boolean NOT NULL,
	"processing_limit_minutes" integer,
	"storage_limit_gb" double precision,
	"usage_period_start" timestamp with time zone,
	"used_ai_answers" integer NOT NULL,
	"used_processing_seconds" integer NOT NULL,
	"used_storage_bytes" bigint NOT NULL,
	"pending_email" varchar(254),
	CONSTRAINT "users_username_key" UNIQUE("username"),
	CONSTRAINT "users_email_key" UNIQUE("email"),
	CONSTRAINT "users_max_video_upload_size_mb_check" CHECK (max_video_upload_size_mb >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "api_keys" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "api_keys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"prefix" varchar(12) NOT NULL,
	"hashed_key" varchar(64) NOT NULL,
	"last_used_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"user_id" bigint NOT NULL,
	"access_level" varchar(20) NOT NULL,
	CONSTRAINT "api_keys_hashed_key_key" UNIQUE("hashed_key")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "account_deletion_requests" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_deletion_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reason" text NOT NULL,
	"requested_at" timestamp with time zone NOT NULL,
	"user_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "videos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "videos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"file" varchar(100) NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"uploaded_at" timestamp with time zone NOT NULL,
	"transcript" text NOT NULL,
	"status" varchar(20) NOT NULL,
	"error_message" text NOT NULL,
	"user_id" bigint NOT NULL,
	"source_type" varchar(20) NOT NULL,
	"source_url" varchar(200) NOT NULL,
	"youtube_video_id" varchar(32) NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "video_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "video_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"user_id" bigint NOT NULL,
	"share_slug" varchar(64),
	"display_order" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "video_group_members" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "video_group_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"added_at" timestamp with time zone NOT NULL,
	"order" integer NOT NULL,
	"group_id" bigint NOT NULL,
	"video_id" bigint NOT NULL,
	CONSTRAINT "video_group_members_group_video_uniq" UNIQUE("group_id","video_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tags" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tags_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"color" varchar(20) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "tags_user_id_name_uniq" UNIQUE("name","user_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "video_tags" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "video_tags_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"added_at" timestamp with time zone NOT NULL,
	"tag_id" bigint NOT NULL,
	"video_id" bigint NOT NULL,
	CONSTRAINT "video_tags_video_tag_uniq" UNIQUE("tag_id","video_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chat_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"question" text NOT NULL,
	"answer" text NOT NULL,
	"citations" jsonb NOT NULL,
	"is_shared_origin" boolean NOT NULL,
	"feedback" varchar(4),
	"created_at" timestamp with time zone NOT NULL,
	"user_id" bigint NOT NULL,
	"group_id" bigint NOT NULL,
	"retrieved_contexts" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chat_log_evaluations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_log_evaluations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"status" varchar(20) NOT NULL,
	"faithfulness" double precision,
	"answer_relevancy" double precision,
	"context_precision" double precision,
	"error_message" text NOT NULL,
	"evaluated_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"chat_log_id" bigint NOT NULL,
	CONSTRAINT "chat_log_evaluations_chat_log_id_key" UNIQUE("chat_log_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "group_evaluation_snapshots" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "group_evaluation_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sample_count" integer NOT NULL,
	"faithfulness_mean" double precision,
	"answer_relevancy_mean" double precision,
	"samples" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"group_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"context_precision_mean" double precision,
	CONSTRAINT "group_evaluation_snapshots_group_id_key" UNIQUE("group_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "plog_build_jobs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plog_build_jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"status" varchar(20) NOT NULL,
	"error_message" text NOT NULL,
	"input_tokens" integer NOT NULL,
	"output_tokens" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone,
	"video_id" bigint NOT NULL,
	CONSTRAINT "plog_build_jobs_input_tokens_check" CHECK (input_tokens >= 0),
	CONSTRAINT "plog_build_jobs_output_tokens_check" CHECK (output_tokens >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "plog_summary_nodes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plog_summary_nodes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"level" smallint NOT NULL,
	"text" text NOT NULL,
	"start_sec" double precision NOT NULL,
	"end_sec" double precision NOT NULL,
	"scene_indices" jsonb NOT NULL,
	"embedding" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"parent_id" bigint,
	"video_id" bigint NOT NULL,
	CONSTRAINT "plog_summary_nodes_level_check" CHECK (level >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "plog_concepts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plog_concepts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"label" varchar(255) NOT NULL,
	"node_type" varchar(20) NOT NULL,
	"intro_sec" double precision NOT NULL,
	"source_quote" text NOT NULL,
	"embedding" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"video_id" bigint NOT NULL,
	CONSTRAINT "plog_concepts_label_video_uniq" UNIQUE("label","video_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "plog_edges" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plog_edges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"edge_type" varchar(32) NOT NULL,
	"quote" text NOT NULL,
	"validation_status" varchar(20) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"source_id" bigint NOT NULL,
	"target_id" bigint NOT NULL,
	"video_id" bigint NOT NULL,
	CONSTRAINT "plog_edges_typed_pair_uniq" UNIQUE("edge_type","source_id","target_id","video_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "plog_learning_objects" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plog_learning_objects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"opening_question" text NOT NULL,
	"hint_ladder" jsonb NOT NULL,
	"misconceptions" jsonb NOT NULL,
	"canonical_order" jsonb NOT NULL,
	"worked_examples" jsonb NOT NULL,
	"waypoints" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"concept_id" bigint NOT NULL,
	CONSTRAINT "plog_learning_objects_concept_id_key" UNIQUE("concept_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "learner_concept_states" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "learner_concept_states_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reached" boolean NOT NULL,
	"hint_index" smallint NOT NULL,
	"last_grade" varchar(32) NOT NULL,
	"active" boolean NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"concept_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "learner_concept_states_concept_user_uniq" UNIQUE("concept_id","user_id"),
	CONSTRAINT "learner_concept_states_hint_index_check" CHECK (hint_index >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scene_embeddings" (
	"id" uuid PRIMARY KEY NOT NULL,
	"content" text NOT NULL,
	"embedding" vector(1024) NOT NULL,
	"user_id" bigint,
	"video_id" bigint,
	"langchain_metadata" json
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "oauth_applications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth_applications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_id" varchar(100) NOT NULL,
	"redirect_uris" text NOT NULL,
	"client_type" varchar(32) NOT NULL,
	"authorization_grant_type" varchar(44) NOT NULL,
	"client_secret" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"user_id" bigint,
	"skip_authorization" boolean NOT NULL,
	"created" timestamp with time zone NOT NULL,
	"updated" timestamp with time zone NOT NULL,
	"algorithm" varchar(5) NOT NULL,
	"post_logout_redirect_uris" text NOT NULL,
	"hash_client_secret" boolean NOT NULL,
	"allowed_origins" text NOT NULL,
	CONSTRAINT "oauth_applications_client_id_key" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "oauth_grants" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth_grants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	"redirect_uri" text NOT NULL,
	"scope" text NOT NULL,
	"application_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"created" timestamp with time zone NOT NULL,
	"updated" timestamp with time zone NOT NULL,
	"code_challenge" varchar(128) NOT NULL,
	"code_challenge_method" varchar(10) NOT NULL,
	"nonce" varchar(255) NOT NULL,
	"claims" text NOT NULL,
	CONSTRAINT "oauth_grants_code_key" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "oauth_id_tokens" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth_id_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"jti" uuid NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	"scope" text NOT NULL,
	"created" timestamp with time zone NOT NULL,
	"updated" timestamp with time zone NOT NULL,
	"application_id" bigint,
	"user_id" bigint,
	CONSTRAINT "oauth_id_tokens_jti_key" UNIQUE("jti")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "oauth_access_tokens" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth_access_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token" text NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	"scope" text NOT NULL,
	"application_id" bigint,
	"user_id" bigint,
	"created" timestamp with time zone NOT NULL,
	"updated" timestamp with time zone NOT NULL,
	"source_refresh_token_id" bigint,
	"id_token_id" bigint,
	"token_checksum" varchar(64) NOT NULL,
	CONSTRAINT "oauth_access_tokens_source_refresh_token_id_key" UNIQUE("source_refresh_token_id"),
	CONSTRAINT "oauth_access_tokens_id_token_id_key" UNIQUE("id_token_id"),
	CONSTRAINT "oauth_access_tokens_token_checksum_key" UNIQUE("token_checksum")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "oauth_refresh_tokens" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth_refresh_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token" varchar(255) NOT NULL,
	"access_token_id" bigint,
	"application_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"created" timestamp with time zone NOT NULL,
	"updated" timestamp with time zone NOT NULL,
	"revoked" timestamp with time zone,
	"token_family" uuid,
	CONSTRAINT "oauth_refresh_tokens_token_revoked_uniq" UNIQUE("token","revoked"),
	CONSTRAINT "oauth_refresh_tokens_access_token_id_key" UNIQUE("access_token_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "oauth_device_grants" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth_device_grants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"device_code" varchar(100) NOT NULL,
	"user_code" varchar(100) NOT NULL,
	"scope" varchar(64),
	"interval" integer NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	"status" varchar(64) NOT NULL,
	"client_id" varchar(100) NOT NULL,
	"last_checked" timestamp with time zone NOT NULL,
	"user_id" bigint,
	CONSTRAINT "oauth_device_grants_device_code_key" UNIQUE("device_code")
);
--> statement-breakpoint
-- Foreign keys
ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "account_deletion_requests" ADD CONSTRAINT "account_deletion_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "videos" ADD CONSTRAINT "videos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "video_groups" ADD CONSTRAINT "video_groups_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "video_group_members" ADD CONSTRAINT "video_group_members_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."video_groups"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "video_group_members" ADD CONSTRAINT "video_group_members_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tags" ADD CONSTRAINT "tags_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "video_tags" ADD CONSTRAINT "video_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "video_tags" ADD CONSTRAINT "video_tags_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "chat_logs" ADD CONSTRAINT "chat_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "chat_logs" ADD CONSTRAINT "chat_logs_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."video_groups"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "chat_log_evaluations" ADD CONSTRAINT "chat_log_evaluations_chat_log_id_fkey" FOREIGN KEY ("chat_log_id") REFERENCES "public"."chat_logs"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "group_evaluation_snapshots" ADD CONSTRAINT "group_evaluation_snapshots_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."video_groups"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "group_evaluation_snapshots" ADD CONSTRAINT "group_evaluation_snapshots_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "plog_build_jobs" ADD CONSTRAINT "plog_build_jobs_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "plog_summary_nodes" ADD CONSTRAINT "plog_summary_nodes_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."plog_summary_nodes"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "plog_summary_nodes" ADD CONSTRAINT "plog_summary_nodes_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "plog_concepts" ADD CONSTRAINT "plog_concepts_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "plog_edges" ADD CONSTRAINT "plog_edges_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "public"."plog_concepts"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "plog_edges" ADD CONSTRAINT "plog_edges_target_id_fkey" FOREIGN KEY ("target_id") REFERENCES "public"."plog_concepts"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "plog_edges" ADD CONSTRAINT "plog_edges_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "plog_learning_objects" ADD CONSTRAINT "plog_learning_objects_concept_id_fkey" FOREIGN KEY ("concept_id") REFERENCES "public"."plog_concepts"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "learner_concept_states" ADD CONSTRAINT "learner_concept_states_concept_id_fkey" FOREIGN KEY ("concept_id") REFERENCES "public"."plog_concepts"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "learner_concept_states" ADD CONSTRAINT "learner_concept_states_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_applications" ADD CONSTRAINT "oauth_applications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_grants" ADD CONSTRAINT "oauth_grants_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "public"."oauth_applications"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_grants" ADD CONSTRAINT "oauth_grants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_id_tokens" ADD CONSTRAINT "oauth_id_tokens_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "public"."oauth_applications"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_id_tokens" ADD CONSTRAINT "oauth_id_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_access_tokens" ADD CONSTRAINT "oauth_access_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_access_tokens" ADD CONSTRAINT "oauth_access_tokens_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "public"."oauth_applications"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_refresh_tokens" ADD CONSTRAINT "oauth_refresh_tokens_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "public"."oauth_applications"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_refresh_tokens" ADD CONSTRAINT "oauth_refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_device_grants" ADD CONSTRAINT "oauth_device_grants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_access_tokens" ADD CONSTRAINT "oauth_access_tokens_source_refresh_token_id_fkey" FOREIGN KEY ("source_refresh_token_id") REFERENCES "public"."oauth_refresh_tokens"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_access_tokens" ADD CONSTRAINT "oauth_access_tokens_id_token_id_fkey" FOREIGN KEY ("id_token_id") REFERENCES "public"."oauth_id_tokens"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "oauth_refresh_tokens" ADD CONSTRAINT "oauth_refresh_tokens_access_token_id_fkey" FOREIGN KEY ("access_token_id") REFERENCES "public"."oauth_access_tokens"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
-- Indexes
CREATE INDEX IF NOT EXISTS "users_email_active_idx" ON "users" USING btree ("email","is_active");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "users_deactivated_at_idx" ON "users" USING btree ("deactivated_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "api_keys_user_id_idx" ON "api_keys" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "api_keys_prefix_idx" ON "api_keys" USING btree ("prefix");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "api_keys_active_name_per_user" ON "api_keys" USING btree ("user_id","name") WHERE (revoked_at IS NULL);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_deletion_requests_user_id_idx" ON "account_deletion_requests" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "videos_user_id_idx" ON "videos" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "videos_status_idx" ON "videos" USING btree ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "video_groups_user_id_idx" ON "video_groups" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "video_group_members_group_id_idx" ON "video_group_members" USING btree ("group_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tags_user_id_idx" ON "tags" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_logs_group_id_idx" ON "chat_logs" USING btree ("group_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scene_embeddings_user_id_idx" ON "scene_embeddings" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scene_embeddings_video_id_idx" ON "scene_embeddings" USING btree ("video_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "oauth_applications_client_id_idx" ON "oauth_applications" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "oauth_access_tokens_user_id_idx" ON "oauth_access_tokens" USING btree ("user_id");
