CREATE TABLE "video_group_invitations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "video_group_invitations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_id" bigint NOT NULL,
	"email" varchar(254) NOT NULL,
	"invited_by_user_id" text NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"delivery_status" varchar(20) DEFAULT 'queued' NOT NULL,
	"token_hash" varchar(64) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"accepted_by_user_id" text,
	"accepted_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"last_sent_at" timestamp with time zone,
	"send_attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	CONSTRAINT "video_group_invitations_token_hash_key" UNIQUE("token_hash"),
	CONSTRAINT "video_group_invitations_status_check" CHECK (status IN ('pending', 'accepted', 'declined', 'expired', 'revoked')),
	CONSTRAINT "video_group_invitations_delivery_status_check" CHECK (delivery_status IN ('queued', 'sent', 'failed')),
	CONSTRAINT "video_group_invitations_send_attempts_check" CHECK (send_attempts >= 0)
);
--> statement-breakpoint
CREATE TABLE "video_group_memberships" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "video_group_memberships_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_id" bigint NOT NULL,
	"user_id" text NOT NULL,
	"invitation_id" bigint,
	"joined_at" timestamp with time zone NOT NULL,
	CONSTRAINT "video_group_memberships_group_user_uniq" UNIQUE("group_id","user_id"),
	CONSTRAINT "video_group_memberships_invitation_id_key" UNIQUE("invitation_id")
);
--> statement-breakpoint
ALTER TABLE "video_group_invitations" ADD CONSTRAINT "video_group_invitations_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."video_groups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_group_invitations" ADD CONSTRAINT "video_group_invitations_invited_by_user_id_fkey" FOREIGN KEY ("invited_by_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_group_invitations" ADD CONSTRAINT "video_group_invitations_accepted_by_user_id_fkey" FOREIGN KEY ("accepted_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_group_memberships" ADD CONSTRAINT "video_group_memberships_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."video_groups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_group_memberships" ADD CONSTRAINT "video_group_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_group_memberships" ADD CONSTRAINT "video_group_memberships_invitation_id_fkey" FOREIGN KEY ("invitation_id") REFERENCES "public"."video_group_invitations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "video_group_invitations_group_status_idx" ON "video_group_invitations" USING btree ("group_id","status");--> statement-breakpoint
CREATE INDEX "video_group_invitations_email_idx" ON "video_group_invitations" USING btree ("email");--> statement-breakpoint
CREATE UNIQUE INDEX "video_group_invitations_pending_email_uniq" ON "video_group_invitations" USING btree ("group_id","email") WHERE status = 'pending';--> statement-breakpoint
CREATE INDEX "video_group_memberships_group_id_idx" ON "video_group_memberships" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "video_group_memberships_user_id_idx" ON "video_group_memberships" USING btree ("user_id");
