CREATE TABLE "external_tasks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "external_tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"kind" varchar(32) NOT NULL,
	"payload" jsonb NOT NULL,
	"dedupe_key" varchar(255) NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"available_at" timestamp with time zone DEFAULT now() NOT NULL,
	"locked_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"effect_applied_at" timestamp with time zone,
	"last_error" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "external_tasks_dedupe_key_key" UNIQUE("dedupe_key"),
	CONSTRAINT "external_tasks_kind_check" CHECK (kind IN ('sqs_job', 'storage_cleanup')),
	CONSTRAINT "external_tasks_attempts_check" CHECK (attempts >= 0)
);
--> statement-breakpoint
CREATE INDEX "external_tasks_ready_idx" ON "external_tasks" USING btree ("available_at","id") WHERE completed_at IS NULL;
