services:
  redis:
    image: "redis:alpine"
    container_name: videoq-redis
    networks:
      - videoq-network

  postgres:
    image: postgres:17
    container_name: videoq-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - videoq-network

  opensearch:
    image: opensearchproject/opensearch:3
    container_name: videoq-opensearch
    env_file:
      - .env
    environment:
      - discovery.type=${DISCOVERY_TYPE}
      - bootstrap.memory_lock=${BOOTSTRAP_MEMORY_LOCK}
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS}
      - DISABLE_INSTALL_DEMO_CONFIG=${DISABLE_INSTALL_DEMO_CONFIG}
      - DISABLE_SECURITY_PLUGIN=${DISABLE_SECURITY_PLUGIN}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - videoq-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3
    container_name: videoq-opensearch-dashboards
    env_file:
      - .env
    depends_on:
      - opensearch
    networks:
      - videoq-network

  nginx:
    image: nginx:alpine
    container_name: videoq-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
    networks:
      - videoq-network

  web:
    build: .
    container_name: videoq-web
    command: gunicorn videoq.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - opensearch
    networks:
      - videoq-network

  worker:
    build: .
    container_name: videoq-worker
    command: celery -A videoq worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - opensearch
    networks:
      - videoq-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: videoq-cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    env_file:
      - .env
    depends_on:
      - nginx
    networks:
      - videoq-network
    restart: unless-stopped

volumes:
  postgres_data:
  opensearch_data:

networks:
  videoq-network:
    driver: bridge 