"""Artifact replacement and successful job completion must commit together."""

import json
import os
import uuid
from contextlib import contextmanager
from types import SimpleNamespace
from unittest.mock import MagicMock

import psycopg
import pytest
from psycopg import sql
from psycopg.rows import dict_row

from worker_python.pipeline import plog_build
from worker_python.tasks import build_plog


@pytest.fixture
def database(monkeypatch):
    url = os.environ.get("DATABASE_URL")
    if not url:
        pytest.skip("DATABASE_URL is required for PostgreSQL integration tests")
    schema = f"plog_persistence_{uuid.uuid4().hex}"
    with psycopg.connect(url, autocommit=True, row_factory=dict_row) as admin:
        admin.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(schema)))
        try:
            admin.execute(sql.SQL("SET search_path TO {}").format(sql.Identifier(schema)))
            admin.execute("""
                CREATE TABLE videos (id integer PRIMARY KEY, transcript text DEFAULT 'Lecture');
                CREATE TABLE plog_build_jobs (
                    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    video_id integer REFERENCES videos(id), status text NOT NULL,
                    error_message text NOT NULL, input_tokens integer NOT NULL,
                    output_tokens integer NOT NULL, created_at timestamptz NOT NULL,
                    updated_at timestamptz NOT NULL, finished_at timestamptz
                );
                CREATE UNIQUE INDEX active_build ON plog_build_jobs(video_id)
                    WHERE status IN ('pending', 'running');
                CREATE TABLE plog_concepts (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    label text, node_type text, intro_sec double precision,
                    source_quote text, embedding jsonb, created_at timestamptz,
                    video_id integer REFERENCES videos(id)
                );
                CREATE TABLE plog_learning_objects (
                    opening_question text, hint_ladder jsonb, misconceptions jsonb,
                    canonical_order jsonb, worked_examples jsonb, waypoints jsonb,
                    created_at timestamptz,
                    concept_id integer REFERENCES plog_concepts(id) ON DELETE CASCADE
                );
                CREATE TABLE plog_edges (
                    edge_type text, quote text, validation_status text, created_at timestamptz,
                    source_id integer REFERENCES plog_concepts(id) ON DELETE CASCADE,
                    target_id integer REFERENCES plog_concepts(id) ON DELETE CASCADE,
                    video_id integer REFERENCES videos(id)
                );
                CREATE TABLE plog_summary_nodes (video_id integer REFERENCES videos(id));
                INSERT INTO videos(id) VALUES (42), (43);
                INSERT INTO plog_concepts (id, video_id, label)
                    VALUES (100, 42, 'Original'), (101, 43, 'Other video');
                INSERT INTO plog_learning_objects (concept_id) VALUES (100), (101);
                INSERT INTO plog_edges (video_id, source_id, target_id)
                    VALUES (42, 100, 100), (43, 101, 101);
                INSERT INTO plog_summary_nodes VALUES (42), (43);
            """)

            @contextmanager
            def connection():
                with psycopg.connect(url, options=f"-c search_path={schema}", row_factory=dict_row) as conn:
                    yield conn

            monkeypatch.setattr(build_plog, "db_connection", connection)
            monkeypatch.setattr(plog_build, "db_connection", connection)
            monkeypatch.setattr(plog_build, "assert_embedding_schema", lambda *_: None)
            yield admin
        finally:
            admin.execute(sql.SQL("DROP SCHEMA {} CASCADE").format(sql.Identifier(schema)))


def test_generated_and_default_hints_are_saved_as_strings(database, monkeypatch):
    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    client = MagicMock()
    client.__enter__.return_value = client
    client.chat.completions.create.return_value = SimpleNamespace(choices=[
        SimpleNamespace(message=SimpleNamespace(content=json.dumps({"concepts": [
            {"label": "Generated", "hints": ["最初のヒント", "Next hint"]},
            {"label": "Missing"},
            {"label": "Empty", "hints": []},
        ]}))),
    ])
    monkeypatch.setattr("openai.OpenAI", MagicMock(return_value=client))
    monkeypatch.setattr(plog_build, "embed_texts", MagicMock(return_value=[[1.0]] * 3))

    build_plog.build_plog_artifacts(42)

    rows = database.execute("""
        SELECT hint_ladder FROM plog_learning_objects lo
        JOIN plog_concepts c ON c.id = lo.concept_id
        WHERE c.video_id = 42 ORDER BY c.id
    """).fetchall()
    assert rows == [
        {"hint_ladder": ["最初のヒント", "Next hint"]},
        {"hint_ladder": ["Think about: Missing"]},
        {"hint_ladder": ["Think about: Empty"]},
    ]


@pytest.mark.parametrize("outcome", ["ready", "empty", "disabled", "extract", "embed", "save", "finish"])
def test_graph_and_job_completion_are_atomic(database, monkeypatch, outcome):
    monkeypatch.setenv("OPENAI_API_KEY", "" if outcome == "disabled" else "test-key")
    monkeypatch.setenv("ENABLE_HEAVY_PIPELINE", "false")
    extract = MagicMock(return_value=[] if outcome == "empty" else [
        {"label": "Evaporation", "intro_sec": 2}, {"label": "Condensation", "intro_sec": 8},
    ])
    embed = MagicMock(return_value=[[1.0], [2.0]])
    monkeypatch.setattr(plog_build, "_extract_concepts", extract)
    monkeypatch.setattr(plog_build, "embed_texts", embed)
    if outcome == "extract":
        extract.side_effect = RuntimeError("extract failed")
    if outcome == "embed":
        embed.side_effect = RuntimeError("embed failed")
    if outcome in {"save", "finish"}:
        database.execute("""
            CREATE FUNCTION reject_write() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN RAISE EXCEPTION 'write rejected'; END $$;
        """)
        if outcome == "save":
            database.execute("""
                CREATE TRIGGER reject_write BEFORE INSERT ON plog_learning_objects
                    FOR EACH ROW EXECUTE FUNCTION reject_write()
            """)
        else:
            database.execute("""
                CREATE TRIGGER reject_write BEFORE UPDATE ON plog_build_jobs
                    FOR EACH ROW WHEN (NEW.status = 'ready') EXECUTE FUNCTION reject_write()
            """)

    tables = ("plog_concepts", "plog_learning_objects", "plog_edges", "plog_summary_nodes")

    def snapshot():
        return {
            table: sorted(database.execute(sql.SQL("SELECT * FROM {}").format(sql.Identifier(table))).fetchall(), key=repr)
            for table in tables
        }

    before = snapshot()
    failed = outcome in {"extract", "embed", "save", "finish"}
    if outcome in {"extract", "embed"}:
        with pytest.raises(RuntimeError, match=f"{outcome} failed"):
            build_plog.build_plog_artifacts(42)
    elif failed:
        with pytest.raises(psycopg.errors.RaiseException, match="write rejected"):
            build_plog.build_plog_artifacts(42)
    else:
        build_plog.build_plog_artifacts(42)

    job = database.execute("SELECT * FROM plog_build_jobs").fetchone()
    assert job["status"] == ("failed" if failed else "ready")
    assert job["finished_at"] is not None
    assert bool(job["error_message"]) == failed
    after = snapshot()
    if failed or outcome == "disabled":
        assert after == before
    else:
        # Other videos retain every field and their learning material.
        for table in tables:
            other = next(row for row in before[table] if row.get("video_id") == 43 or row.get("concept_id") == 101)
            assert other in after[table]
        labels = database.execute("SELECT label FROM plog_concepts WHERE video_id = 42 ORDER BY intro_sec").fetchall()
        assert labels == ([] if outcome == "empty" else [{"label": "Evaporation"}, {"label": "Condensation"}])
        edges = database.execute("SELECT * FROM plog_edges WHERE video_id = 42").fetchall()
        assert len(edges) == (0 if outcome == "empty" else 1)
    if outcome == "disabled":
        extract.assert_not_called()
    if outcome in {"disabled", "empty", "extract"}:
        embed.assert_not_called()
