include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

rest-stats {
  enabled = true
  bind-port = 9325
  bind-hostname = "0.0.0.0"
}

queues {
  videoq-jobs {
    defaultVisibilityTimeout = 15 minutes
    delay = 0 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "videoq-jobs-dlq"
      maxReceiveCount = 5
    }
  }

  videoq-jobs-dlq {
    defaultVisibilityTimeout = 1 minute
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
}
