# Generated by Django 5.2.7 on 2025-12-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_duration_minutes_from_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="is_external_upload",
        ),
    ]
