# Generated by Django 6.0.3 on 2026-03-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_user_max_video_upload_size_mb_alter_user_video_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='related_videos',
            new_name='citations',
        ),
    ]
