# Generated by Django 6.0.3 on 2026-03-29 22:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_user_searchapi_api_key_encrypted'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='videogroup',
            name='videogroup_share_token_idx',
        ),
        migrations.AddField(
            model_name='videogroup',
            name='share_slug',
            field=models.CharField(blank=True, db_index=True, help_text='Share slug', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='videogroup',
            index=models.Index(condition=models.Q(('share_slug__isnull', False)), fields=['share_slug'], name='videogroup_share_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='videogroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('share_slug'), condition=models.Q(('share_slug__isnull', False)), name='videogroup_share_slug_ci_uniq'),
        ),
        migrations.RemoveField(
            model_name='videogroup',
            name='share_token',
        ),
    ]
