# Generated by Django 6.0.4 on 2026-04-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_user_ai_answers_limit_user_is_over_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='retrieved_contexts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ChatLogEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('faithfulness', models.FloatField(blank=True, null=True)),
                ('answer_relevancy', models.FloatField(blank=True, null=True)),
                ('context_precision', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='app.chatlog')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='app_chatlog_status_6ea271_idx')],
            },
        ),
    ]
