# Generated by Django 6.0.4 on 2026-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_user_pending_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videogroup",
            options={"ordering": ["display_order", "-created_at", "id"]},
        ),
        migrations.RemoveIndex(
            model_name="videogroup",
            name="app_videogr_user_id_28e91c_idx",
        ),
        migrations.AddField(
            model_name="videogroup",
            name="display_order",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Display order in the user's group list",
            ),
        ),
        migrations.AddIndex(
            model_name="videogroup",
            index=models.Index(
                fields=["user", "display_order", "-created_at"],
                name="app_videogr_user_id_dd31d1_idx",
            ),
        ),
    ]
