import { ChatStreamController, chatStreamReducer, createInitialChatStreamState } from '@/lib/chatStreamController'
import { applyChatPart, type ChatAnswer, type ChatContentPart } from '@videoq/trpc/chat'

const source = { id: 1, video_id: 10, title: 'Video', start_time: '00:00:05', end_time: '00:00:10' }
const done = { type: 'done' as const, chat_log_id: 99, feedback: null }

describe('structured answer render queue', () => {
  beforeEach(() => vi.useFakeTimers())
  afterEach(() => {
    vi.restoreAllMocks()
    vi.useRealTimers()
  })
  it('coalesces text only within the same segment and delays completion until rendered', async () => {
    const answer: ChatAnswer = { segments: [], sources: [source] }
    const snapshots: ChatContentPart[][] = []
    const onDone = vi.fn()
    const controller = new ChatStreamController({ onAppendParts: parts => {
      snapshots.push(parts)
      parts.forEach(part => applyChatPart(answer, part))
    }, onDone, onError: vi.fn() })
    controller.start()
    controller.handleEvent({ type: 'source', source })
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: 'A' })
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: 'B' })
    controller.handleEvent({ type: 'citation', segmentIndex: 0, sourceId: 1 })
    controller.handleEvent({ type: 'text_delta', segmentIndex: 1, text: 'CDEF' })
    controller.handleEvent(done)
    const complete = controller.complete()
    expect(snapshots).toEqual([])
    expect(onDone).not.toHaveBeenCalled()
    vi.advanceTimersToNextFrame()
    expect(snapshots[0]).toEqual([
      { type: 'text', segmentIndex: 0, text: 'AB' },
      { type: 'citation', segmentIndex: 0, sourceId: 1 },
      { type: 'text', segmentIndex: 1, text: 'CDEF' },
    ])
    await complete
    expect(answer.segments).toEqual([{ text: 'AB', sourceIds: [1] }, { text: 'CDEF', sourceIds: [] }])
    expect(onDone).toHaveBeenCalledExactlyOnceWith(done)
    expect(controller.getSnapshot().framePending).toBe(false)
  })
  it('renders a long received answer in the next frame even while the stream is still open', () => {
    const append = vi.fn(), onDone = vi.fn()
    const controller = new ChatStreamController({ onAppendParts: append, onDone, onError: vi.fn() })
    const text = '早く読める回答🙂'.repeat(500)
    controller.start()
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text })
    vi.advanceTimersToNextFrame()
    expect(append).toHaveBeenCalledExactlyOnceWith([{ type: 'text', segmentIndex: 0, text }])
    expect(onDone).not.toHaveBeenCalled()
    controller.dispose()
  })
  it('renders literal brackets and emoji together without a typing delay', () => {
    const rendered: ChatContentPart[][] = []
    const controller = new ChatStreamController({ onAppendParts: p => rendered.push(p), onDone: vi.fn(), onError: vi.fn() })
    controller.start()
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: '[1]🙂' })
    vi.advanceTimersToNextFrame()
    expect(rendered).toEqual([[{ type: 'text', segmentIndex: 0, text: '[1]🙂' }]])
    controller.dispose()
  })
  it('schedules one frame per batch and stays idle until more content arrives', () => {
    const requestFrame = vi.spyOn(globalThis, 'requestAnimationFrame')
    const append = vi.fn()
    const controller = new ChatStreamController({ onAppendParts: append, onDone: vi.fn(), onError: vi.fn() })
    controller.start()
    controller.handleEvent({ type: 'searching', search_id: 1, query: 'query' })
    controller.handleEvent({ type: 'source', source })
    expect(requestFrame).not.toHaveBeenCalled()

    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: 'A' })
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: 'B' })
    expect(requestFrame).toHaveBeenCalledTimes(1)
    expect(append).not.toHaveBeenCalled()
    vi.advanceTimersToNextFrame()
    expect(append).toHaveBeenCalledExactlyOnceWith([{ type: 'text', segmentIndex: 0, text: 'AB' }])
    expect(vi.getTimerCount()).toBe(0)
    vi.advanceTimersToNextFrame()
    expect(append).toHaveBeenCalledTimes(1)
    expect(requestFrame).toHaveBeenCalledTimes(1)

    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: 'C' })
    expect(requestFrame).toHaveBeenCalledTimes(2)
    vi.advanceTimersToNextFrame()
    expect(append).toHaveBeenLastCalledWith([{ type: 'text', segmentIndex: 0, text: 'C' }])
    controller.dispose()
  })
  it('preserves empty segments and resolves completion on an empty queue', async () => {
    const append = vi.fn()
    const onDone = vi.fn()
    const controller = new ChatStreamController({ onAppendParts: append, onDone, onError: vi.fn() })
    controller.start()
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: '' })
    controller.handleEvent(done)
    vi.advanceTimersToNextFrame()
    await controller.complete()
    expect(append).toHaveBeenCalledWith([{ type: 'text', segmentIndex: 0, text: '' }])
    expect(onDone).toHaveBeenCalledOnce()
  })
  it.each(['error', 'abort', 'restart', 'dispose'])('clears queued text and pending completion on %s', async action => {
    const append = vi.fn(), onDone = vi.fn(), onError = vi.fn()
    const controller = new ChatStreamController({ onAppendParts: append, onDone, onError })
    controller.start()
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: 'old content' })
    const waiting = controller.waitForDrainCompletion()
    if (action === 'error') controller.handleEvent({ type: 'error', code: 'FAILED', message: 'failed' })
    else if (action === 'abort') controller.abort()
    else if (action === 'restart') controller.start()
    else controller.dispose()
    await waiting
    vi.advanceTimersToNextFrame()
    expect(append).not.toHaveBeenCalled()
    expect(onDone).not.toHaveBeenCalled()
    expect(controller.getSnapshot().queuedParts).toEqual([])
    expect(controller.getSnapshot().framePending).toBe(false)
  })
  it.each(['done', 'complete'])('finishes in a hidden tab on %s without an animation frame', async terminal => {
    vi.spyOn(document, 'hidden', 'get').mockReturnValue(true)
    const answer: ChatAnswer = { segments: [], sources: [source] }
    const append = vi.fn((parts: ChatContentPart[]) => parts.forEach(part => applyChatPart(answer, part)))
    const onDone = vi.fn(() => {
      expect(answer.segments).toEqual([{ text: 'Hidden answer', sourceIds: [1] }])
    })
    const controller = new ChatStreamController({ onAppendParts: append, onDone, onError: vi.fn() })
    controller.start()
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: 'Hidden answer' })
    controller.handleEvent({ type: 'citation', segmentIndex: 0, sourceId: 1 })
    expect(append).not.toHaveBeenCalled()

    if (terminal === 'done') controller.handleEvent(done)
    await controller.complete()
    expect(append).toHaveBeenCalledTimes(1)
    expect(answer.segments).toEqual([{ text: 'Hidden answer', sourceIds: [1] }])
    expect(onDone).toHaveBeenCalledTimes(terminal === 'done' ? 1 : 0)
    expect(controller.getSnapshot().framePending).toBe(false)
    vi.advanceTimersToNextFrame()
    expect(append).toHaveBeenCalledTimes(1)
  })
  it('finishes if the tab becomes hidden while the final frame is pending', async () => {
    const hidden = vi.spyOn(document, 'hidden', 'get').mockReturnValue(false)
    const append = vi.fn(), onDone = vi.fn()
    const controller = new ChatStreamController({ onAppendParts: append, onDone, onError: vi.fn() })
    controller.start()
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: 'Final answer' })
    controller.handleEvent(done)
    const complete = controller.complete()
    expect(onDone).not.toHaveBeenCalled()

    hidden.mockReturnValue(true)
    document.dispatchEvent(new Event('visibilitychange'))
    await complete
    expect(append).toHaveBeenCalledExactlyOnceWith([{ type: 'text', segmentIndex: 0, text: 'Final answer' }])
    expect(onDone).toHaveBeenCalledExactlyOnceWith(done)
    expect(controller.getSnapshot().framePending).toBe(false)
    vi.advanceTimersToNextFrame()
    expect(append).toHaveBeenCalledTimes(1)
  })
  it('resumes partial text on the next frame when the tab becomes visible again', async () => {
    const hidden = vi.spyOn(document, 'hidden', 'get').mockReturnValue(true)
    const append = vi.fn(), onDone = vi.fn()
    const controller = new ChatStreamController({ onAppendParts: append, onDone, onError: vi.fn() })
    controller.start()
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: 'First' })
    expect(append).not.toHaveBeenCalled()

    hidden.mockReturnValue(false)
    document.dispatchEvent(new Event('visibilitychange'))
    vi.advanceTimersToNextFrame()
    expect(append).toHaveBeenCalledExactlyOnceWith([{ type: 'text', segmentIndex: 0, text: 'First' }])
    expect(onDone).not.toHaveBeenCalled()
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: ' second' })
    controller.handleEvent(done)
    vi.advanceTimersToNextFrame()
    await controller.complete()
    expect(append).toHaveBeenCalledTimes(2)
    expect(append).toHaveBeenLastCalledWith([{ type: 'text', segmentIndex: 0, text: ' second' }])
    expect(onDone).toHaveBeenCalledExactlyOnceWith(done)
  })
  it.each(['abort', 'restart', 'dispose'])('does not apply pending completion after %s when visibility changes', async action => {
    const hidden = vi.spyOn(document, 'hidden', 'get').mockReturnValue(false)
    const append = vi.fn(), onDone = vi.fn()
    const controller = new ChatStreamController({ onAppendParts: append, onDone, onError: vi.fn() })
    controller.start()
    controller.handleEvent({ type: 'text_delta', segmentIndex: 0, text: 'Old answer' })
    controller.handleEvent(done)
    const complete = controller.complete()
    if (action === 'restart') controller.start()
    else if (action === 'dispose') controller.dispose()
    else controller.abort()

    hidden.mockReturnValue(true)
    document.dispatchEvent(new Event('visibilitychange'))
    await complete
    vi.advanceTimersToNextFrame()
    expect(append).not.toHaveBeenCalled()
    expect(onDone).not.toHaveBeenCalled()
    expect(controller.getSnapshot().framePending).toBe(false)
  })
  it('ignores non-content progress in the render queue', () => {
    const initial = createInitialChatStreamState()
    expect(chatStreamReducer(initial, { type: 'stream_event', event: { type: 'source', source } })).toBe(initial)
    expect(chatStreamReducer(initial, { type: 'stream_event', event: { type: 'searching', search_id: 1, query: 'query' } })).toBe(initial)
  })
})
