# Generated by Django 5.2.4 on 2025-07-19 23:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StripeWebhookEvent",
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_subscribed",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="subscription_plan",
        ),
        migrations.RemoveField(
            model_name="videogroup",
            name="previous_share_token",
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                storage=app.models.SafeLocalFileStorage(),
                upload_to=app.models.user_directory_path,
            ),
        ),
        migrations.DeleteModel(
            name="SubscriptionChangeLog",
        ),
    ]
