# Generated by Django 5.2.6 on 2025-09-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="is_visible",
            field=models.BooleanField(
                default=True, help_text="動画の表示/非表示を制御"
            ),
        ),
    ]
