# Generated by Django 5.2.6 on 2025-09-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_add_video_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_openai_api_key",
            field=models.TextField(
                blank=True, help_text="Encrypted OpenAI API key", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="video_limit",
            field=models.IntegerField(
                blank=True,
                help_text="Video limit for this user (applies default limit if null)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="is_visible",
            field=models.BooleanField(
                default=True, help_text="Control video visibility"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="videogroup",
            name="description",
            field=models.TextField(blank=True, help_text="Group description"),
        ),
        migrations.AlterField(
            model_name="videogroup",
            name="name",
            field=models.CharField(help_text="Group name", max_length=255),
        ),
        migrations.AlterField(
            model_name="videogroup",
            name="share_token",
            field=models.CharField(
                blank=True,
                help_text="Share token",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="videogroupchatlog",
            name="approx_size",
            field=models.BigIntegerField(
                default=0, help_text="Approximate size (bytes)"
            ),
        ),
        migrations.AlterField(
            model_name="videogroupchatlog",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Session ID for shared access",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="videogroupchatlog",
            name="source",
            field=models.CharField(
                choices=[("owner", "Owner"), ("share", "Share")], max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="videogroupmember",
            name="order",
            field=models.IntegerField(default=0, help_text="Order within the group"),
        ),
    ]
