# Generated by Django 5.2.4 on 2025-08-13 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_tag_video_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoGroupChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("owner", "オーナー"), ("share", "共有")],
                        max_length=16,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="共有アクセスのセッションID",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True, default="")),
                ("timestamp_results", models.JSONField(blank=True, null=True)),
                ("related_questions", models.JSONField(blank=True, null=True)),
                ("requester_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_logs",
                        to="app.videogroup",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["group", "created_at"],
                        name="app_videogr_group_i_1dc827_idx",
                    ),
                    models.Index(
                        fields=["owner", "created_at"],
                        name="app_videogr_owner_i_8402df_idx",
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="app_videogr_source_c50655_idx",
                    ),
                ],
            },
        ),
    ]
