# Generated by Django 5.2.4 on 2025-08-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_videogroupchatlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogroupchatlog",
            name="approx_size",
            field=models.BigIntegerField(default=0, help_text="概算サイズ（バイト）"),
        ),
    ]
