# Generated by Django 5.2.5 on 2025-08-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_videogroupchatlog_approx_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="video_limit",
            field=models.IntegerField(
                blank=True,
                help_text="このユーザーの動画数上限（nullならデフォルト上限を適用）",
                null=True,
            ),
        ),
    ]
