# Generated by Django 5.2.5 on 2025-08-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_user_video_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ban_reason",
        ),
    ]
