import { useState, type ComponentProps } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { expect, fn, waitFor, within } from 'storybook/test';
import i18n from '@/i18n/config';
import { Button } from '@/components/ui/button';
import { authFixtures } from '../../../../.storybook/fixtures/auth';
import { course, libraryVideos, longText } from '../../../../.storybook/fixtures/detail';
import { tags } from '../../../../.storybook/fixtures/tags';
import { addError, addRequest, libraryHandler, listRequest, loadError, type LibraryScenario } from '../../../../.storybook/mocks/pickFromLibrary';
import { PickFromLibraryDialog } from './PickFromLibraryDialog';

const label = (key: string) => i18n.t(`videos.courseDetail.${key}`);
function Example(args: ComponentProps<typeof PickFromLibraryDialog>) {
  const [open, setOpen] = useState(args.isOpen);
  return <><Button onClick={() => setOpen(true)}>{label('pickFromLibrary')}</Button>
    <PickFromLibraryDialog {...args} isOpen={open} onOpenChange={value => { args.onOpenChange(value); setOpen(value); }} />
  </>;
}
const meta = {
  title: 'Video/PickFromLibraryDialog', component: PickFromLibraryDialog,
  args: { isOpen: false, courseId: course.id, course, onOpenChange: fn(), onVideosAdded: fn() },
  render: args => <Example {...args} />,
  parameters: { api: { auth: authFixtures.user }, docs: { story: { inline: false, height: '950px' } } },
  beforeEach({ parameters, msw }) { msw.use(libraryHandler(parameters.library as LibraryScenario | undefined)); },
  async play({ canvas, userEvent }) { await userEvent.click(canvas.getByRole('button', { name: label('pickFromLibrary') })); await expect(within(canvas.getByRole('dialog')).getByRole('heading', { level: 2 })).toHaveFocus(); },
} satisfies Meta<typeof PickFromLibraryDialog>;
export default meta;
type Story = StoryObj<typeof meta>;
type Context = Parameters<NonNullable<Story['play']>>[0];
const main = (context: Context) => context.canvas.getByRole('dialog', { name: label('pickFromLibrary') });
async function loaded(context: Context) { await meta.play(context); const dialog = within(main(context)); await dialog.findAllByRole('checkbox'); return dialog; }
async function selectTwo(context: Context) { const dialog = await loaded(context); const boxes = dialog.getAllByRole('checkbox'); await context.userEvent.click(boxes[0]); await context.userEvent.click(boxes[1]); return dialog; }
async function add(context: Context) { const dialog = await selectTwo(context); await context.userEvent.click(dialog.getByRole('button', { name: label('add') })); await waitFor(() => expect(addRequest).toHaveBeenCalledWith({ courseId: course.id, videoIds: [11, 12] })); return dialog; }

export const Loaded: Story = { async play(context) { const dialog = await loaded(context); await expect(dialog.getAllByRole('checkbox')).toHaveLength(3); await expect(dialog.queryByText(libraryVideos[0].title)).not.toBeInTheDocument(); await expect(dialog.getByRole('button', { name: label('add') })).toBeDisabled(); } };
export const Loading: Story = { parameters: { library: { load: 'pending' } satisfies LibraryScenario }, async play(context) { await meta.play(context); await expect(within(main(context)).getByRole('progressbar')).toBeVisible(); } };
export const LoadFailed: Story = { parameters: { library: { load: 'error' } satisfies LibraryScenario }, async play(context) { await meta.play(context); await expect(await within(main(context)).findByRole('alert')).toHaveTextContent(loadError); await expect(within(main(context)).queryByText(label('noAvailableVideos'))).not.toBeInTheDocument(); } };
export const Empty: Story = { parameters: { library: { videos: [] } satisfies LibraryScenario }, async play(context) { await meta.play(context); const dialog = within(main(context)); await expect(await dialog.findByText(label('noAvailableVideos'))).toBeVisible(); await expect(dialog.getByRole('link', { name: i18n.t('videos.goToLibrary') })).toHaveAttribute('href', '/videos'); } };
export const AlreadyInCourse: Story = { parameters: { library: { videos: [libraryVideos[0]] } satisfies LibraryScenario }, async play(context) { await Empty.play!(context); } };
export const Search: Story = { async play(context) { const dialog = await loaded(context); await context.userEvent.type(dialog.getByRole('textbox'), '復習'); await waitFor(() => expect(listRequest).toHaveBeenLastCalledWith(expect.objectContaining({ q: '復習' }))); await waitFor(() => expect(dialog.getAllByRole('checkbox')).toHaveLength(1)); await expect(dialog.getByText('ベクトルの復習')).toBeVisible(); } };
export const NoSearchResults: Story = { async play(context) { const dialog = await loaded(context); await context.userEvent.type(dialog.getByRole('textbox'), 'not-found'); await expect(await dialog.findByText(label('noAvailableVideos'))).toBeVisible(); await expect(dialog.getByRole('button', { name: label('selectAll') })).toBeDisabled(); } };
export const StatusFilter: Story = { async play(context) { const dialog = await loaded(context); await context.userEvent.click(dialog.getByRole('combobox', { name: i18n.t('videos.detail.statusSection') })); await context.userEvent.click(context.canvas.getByRole('option', { name: label('statusFilter.processing') })); await waitFor(() => expect(listRequest).toHaveBeenLastCalledWith(expect.objectContaining({ status: 'processing' }))); await waitFor(() => expect(dialog.getAllByRole('checkbox')).toHaveLength(1)); await expect(dialog.getByText('座標変換の演習')).toBeVisible(); } };
export const TagFilter: Story = { async play(context) { const dialog = await loaded(context); const tag = dialog.getByRole('button', { name: new RegExp(tags[0].name) }); await context.userEvent.click(tag); await waitFor(() => expect(listRequest).toHaveBeenLastCalledWith(expect.objectContaining({ tags: [1] }))); await waitFor(() => expect(dialog.getAllByRole('checkbox')).toHaveLength(2)); await expect(tag).toHaveAttribute('aria-pressed', 'true'); await context.userEvent.click(dialog.getByRole('button', { name: i18n.t('tags.filter.clear') })); await waitFor(() => expect(dialog.getAllByRole('checkbox')).toHaveLength(3)); } };
export const Ordering: Story = { async play(context) { const dialog = await loaded(context); await context.userEvent.click(dialog.getByRole('combobox', { name: i18n.t('videos.list.sortLabel') })); await context.userEvent.click(context.canvas.getByRole('option', { name: label('ordering.titleDesc') })); await waitFor(() => expect(listRequest).toHaveBeenLastCalledWith(expect.objectContaining({ ordering: 'title_desc' }))); await waitFor(() => expect(dialog.getAllByRole('checkbox')).toHaveLength(3)); const expected = libraryVideos.slice(1).sort((a,b) => b.title.localeCompare(a.title, 'ja')); await expect(dialog.getAllByRole('checkbox')[0]).toHaveAccessibleName(new RegExp(expected[0].title)); } };
export const MultipleSelection: Story = { async play(context) { const dialog = await selectTwo(context); await expect(dialog.getAllByRole('checkbox', { checked: true })).toHaveLength(2); await expect(dialog.getByRole('button', { name: label('add') })).toBeEnabled(); } };
export const SelectAllAndClear: Story = { async play(context) { const dialog = await loaded(context); await context.userEvent.click(dialog.getByRole('button', { name: label('selectAll') })); await expect(dialog.getAllByRole('checkbox', { checked: true })).toHaveLength(3); await context.userEvent.click(dialog.getByRole('button', { name: label('clearSelection') })); await expect(dialog.queryAllByRole('checkbox', { checked: true })).toHaveLength(0); await expect(dialog.getByRole('button', { name: label('add') })).toBeDisabled(); } };
export const Adding: Story = { parameters: { library: { add: 'pending' } satisfies LibraryScenario }, async play(context) { const dialog = await add(context); for (const control of main(context).querySelectorAll('input,button')) await expect(control).toBeDisabled(); await expect(dialog.getByRole('button', { name: i18n.t('common.actions.cancel') })).toBeDisabled(); main(context).dispatchEvent(new Event('cancel', { cancelable: true })); await expect(main(context)).toBeVisible(); await expect(context.args.onOpenChange).not.toHaveBeenCalled(); } };
export const AddFailed: Story = { parameters: { library: { add: 'error' } satisfies LibraryScenario }, async play(context) { const dialog = await add(context); const error = await dialog.findByRole('alert'); await expect(error).toHaveTextContent(addError); await waitFor(() => expect(error.parentElement).toHaveFocus()); await expect(dialog.getAllByRole('checkbox', { checked: true })).toHaveLength(2); await expect(dialog.getByRole('button', { name: label('add') })).toBeEnabled(); } };
export const RetryAdd: Story = { parameters: { library: { add: 'retry' } satisfies LibraryScenario }, async play(context) { await AddFailed.play!(context); await context.userEvent.click(within(main(context)).getByRole('button', { name: label('add') })); await waitFor(() => expect(context.canvas.queryByRole('dialog')).not.toBeInTheDocument()); await expect(addRequest).toHaveBeenCalledTimes(2); await expect(context.args.onVideosAdded).toHaveBeenCalledTimes(1); } };
export const AddSucceeded: Story = { async play(context) { await add(context); await waitFor(() => expect(context.canvas.queryByRole('dialog')).not.toBeInTheDocument()); await expect(context.args.onVideosAdded).toHaveBeenCalledTimes(1); await expect(context.canvas.getByRole('button', { name: label('pickFromLibrary') })).toHaveFocus(); } };
export const SkippedAlreadyAdded: Story = { parameters: { library: { skipped: 1 } satisfies LibraryScenario }, async play(context) { await AddSucceeded.play!(context); await expect(context.canvas.getByText(i18n.t('videos.courseDetail.addResult', { added: 1, skipped: 1 }))).toBeVisible(); } };
export const KeyboardAndClose: Story = { async play(context) { const dialog = await loaded(context); await context.userEvent.tab(); await expect(dialog.getByRole('textbox')).toHaveFocus(); const checkbox = dialog.getAllByRole('checkbox')[0]; checkbox.focus(); await context.userEvent.keyboard(' '); await expect(checkbox).toBeChecked(); main(context).dispatchEvent(new Event('cancel', { cancelable: true })); await waitFor(() => expect(context.canvas.queryByRole('dialog')).not.toBeInTheDocument()); await expect(context.canvas.getByRole('button', { name: label('pickFromLibrary') })).toHaveFocus(); } };
export const ManyVideos: Story = { parameters: { library: { videos: Array.from({ length: 30 }, (_, index) => ({ ...libraryVideos[1], id: 100 + index, title: `講義 ${index + 1}` })) } satisfies LibraryScenario }, async play(context) { const dialog = await loaded(context); await expect(dialog.getAllByRole('checkbox')).toHaveLength(24); await context.userEvent.click(dialog.getByRole('button', { name: label('loadMoreVideos') })); await waitFor(() => expect(dialog.getAllByRole('checkbox')).toHaveLength(30)); dialog.getAllByRole('checkbox').at(-1)!.scrollIntoView({ block: 'nearest' }); await expect(dialog.getByRole('button', { name: label('add') }).getBoundingClientRect().bottom).toBeLessThanOrEqual(context.canvasElement.ownerDocument.documentElement.clientHeight); } };
export const LongContentMobile: Story = { globals: { viewport: { value: 'mobile', isRotated: false } }, parameters: { library: { videos: [{ ...libraryVideos[1], title: longText, description: longText }] } satisfies LibraryScenario }, async play(context) { await loaded(context); const content = main(context).querySelector('[data-slot="dialog-content"]')!; await expect(content.scrollWidth).toBeLessThanOrEqual(content.clientWidth); } };
export const EnglishMobile: Story = { globals: { locale: 'en', viewport: { value: 'mobile', isRotated: false } }, parameters: { library: { videos: libraryVideos.slice(1).map((video, index) => ({ ...video, title: `Lesson ${index + 1}: Rotation matrices`, description: 'Learn coordinate transformations.' })) } satisfies LibraryScenario }, async play(context) { await loaded(context); } };
