import pg from "pg";
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import * as courses from "../src/features/courses/service";
import { getCourseDetail, getCourseDetailByShareSlug, getCourseInfo, listCoursesPage } from "../src/repositories/course-repository";
import { getTagDetail } from "../src/repositories/tag-repository";
import { callMcpTool } from "../src/lib/mcp-tools";
import { COURSE_DESCRIPTION_LIMIT, VIDEO_DESCRIPTION_LIMIT } from "../src/lib/rag-course-info";
import * as media from "../src/integrations/media";
import type { Bindings } from "../src/types/bindings";

const databaseUrl = process.env.QUOTA_TEST_DATABASE_URL;
const describeWithPostgres = databaseUrl ? describe : describe.skip;

describeWithPostgres("course reads on PostgreSQL", () => {
  const schema = `course_reads_${crypto.randomUUID().replaceAll("-", "")}`;
  let admin: pg.Client;
  let env: Bindings;

  beforeAll(async () => {
    admin = new pg.Client({ connectionString: databaseUrl });
    await admin.connect();
    await admin.query(`
      CREATE SCHEMA "${schema}";
      SET search_path TO "${schema}";
      CREATE TABLE users (id text PRIMARY KEY);
      CREATE TABLE video_courses (
        id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
        user_id text NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '',
        display_order integer NOT NULL DEFAULT 0, share_slug text,
        created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
      );
      CREATE TABLE videos (
        id bigint PRIMARY KEY, user_id text NOT NULL, title text NOT NULL,
        description text NOT NULL DEFAULT '', file text NOT NULL DEFAULT 'videos/example.mp4',
        uploaded_at timestamptz NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'completed',
        source_type text NOT NULL DEFAULT 'uploaded', source_url text NOT NULL DEFAULT '',
        youtube_video_id text NOT NULL DEFAULT ''
      );
      CREATE TABLE video_course_members (
        id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
        course_id bigint NOT NULL REFERENCES video_courses ON DELETE CASCADE, video_id bigint NOT NULL REFERENCES videos,
        "order" integer NOT NULL DEFAULT 0, added_at timestamptz NOT NULL DEFAULT now()
      );
      CREATE TABLE video_course_memberships (course_id bigint NOT NULL, user_id text NOT NULL);
      CREATE TABLE tags (
        id bigint PRIMARY KEY, user_id text NOT NULL, name text NOT NULL, color text NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now()
      );
      CREATE TABLE video_tags (id bigint PRIMARY KEY, video_id bigint REFERENCES videos, tag_id bigint REFERENCES tags);
      CREATE TABLE mcp_idempotency_records (
        user_id text NOT NULL, action text NOT NULL, key text NOT NULL,
        request_hash text NOT NULL, resource_id bigint NOT NULL, created_at timestamptz NOT NULL,
        PRIMARY KEY (user_id, action, key)
      );
      INSERT INTO users VALUES ('owner'), ('member'), ('outsider'), ('creator');
      INSERT INTO video_courses (id, user_id, name, share_slug) VALUES
        (10, 'owner', 'Course', 'shared-course'), (20, 'outsider', 'Private', NULL),
        (30, 'owner', 'Empty', NULL);
      INSERT INTO videos (id, user_id, title) VALUES
        (1, 'owner', 'First'), (2, 'owner', 'Second'), (3, 'outsider', 'Private video'),
        (4, 'creator', 'Created video');
      INSERT INTO video_course_members (id, course_id, video_id, "order", added_at) VALUES
        (1, 10, 1, 3, '2026-09-01'), (2, 10, 2, 3, '2026-09-01'), (3, 20, 3, 0, '2026-09-01');
      INSERT INTO video_course_memberships VALUES (10, 'member');
      INSERT INTO tags (id, user_id, name, color) VALUES
        (1, 'owner', 'Z tag', 'blue'), (2, 'owner', 'A tag', 'red'),
        (3, 'outsider', 'Private tag', 'green'), (4, 'creator', 'Created tag', 'blue');
      INSERT INTO video_tags VALUES (1, 1, 1), (2, 1, 2), (3, 2, 1), (4, 3, 3), (5, 4, 4);
    `);
    const url = new URL(databaseUrl!);
    url.searchParams.set("options", `-c search_path=${schema}`);
    url.searchParams.set("application_name", schema);
    env = { HYPERDRIVE: { connectionString: url.toString() } } as Bindings;
  });
  afterEach(() => vi.restoreAllMocks());
  afterAll(async () => {
    try { await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); }
    finally { await admin.end(); }
  });

  function statements(calls: unknown[][]) {
    return calls.map(([config]) => typeof config === "string" ? config : (config as pg.QueryConfig).text).join("\n");
  }

  describe("course update responses", () => {
    beforeEach(async () => {
      await admin.query("DELETE FROM video_courses WHERE id = 40");
      await admin.query("INSERT INTO video_courses (id, user_id, name, description, share_slug) VALUES (40, 'owner', 'Original', 'Description', 'editable-course')");
      await admin.query('INSERT INTO video_course_members (course_id, video_id, "order") VALUES (40, 1, 2), (40, 2, 1)');
    });
    afterEach(async () => { await admin.query("DELETE FROM video_courses WHERE id = 40"); });

    it.each([{ name: "Changed" }, { description: "" }, {}])(
      "returns the full course through one connection for %j", async fields => {
        const before = await courses.getCourse(env, 40, "owner");
        const connect = vi.spyOn(pg.Client.prototype, "connect");
        const query = vi.spyOn(pg.Client.prototype, "query");
        expect(await courses.updateUserCourse(env, 40, "owner", fields))
          .toEqual({ course: { ...before, ...fields } });
        expect(connect).toHaveBeenCalledTimes(1);
        const sql = statements(query.mock.calls);
        expect(sql).not.toContain("video_tags");
        // UPDATE RETURNING already contains the course metadata.
        if (Object.keys(fields).length) expect(sql).not.toContain('from "video_courses"');
      },
    );

    it("rolls back the update if its member read fails", async () => {
      await admin.query("ALTER TABLE videos RENAME COLUMN title TO unavailable_title");
      try {
        await expect(courses.updateUserCourse(env, 40, "owner", { name: "Changed" })).rejects.toThrow();
        expect((await admin.query("SELECT name FROM video_courses WHERE id = 40")).rows)
          .toEqual([{ name: "Original" }]);
      } finally {
        await admin.query("ALTER TABLE videos RENAME COLUMN unavailable_title TO title");
      }
    });

    it.each([{ name: "Changed" }, {}])(
      "keeps a complete response when deletion follows the database work (%j)", async fields => {
        const before = await courses.getCourse(env, 40, "owner");
        const end = pg.Client.prototype.end;
        vi.spyOn(pg.Client.prototype, "end").mockImplementation(async function (this: pg.Client) {
          try {
            await admin.query("DELETE FROM video_courses WHERE id = 40");
          } finally {
            await end.call(this);
          }
        });
        expect(await courses.updateUserCourse(env, 40, "owner", fields))
          .toEqual({ course: { ...before, ...fields } });
      },
    );

    it("finishes the database work before resolving media URLs", async () => {
      const end = vi.spyOn(pg.Client.prototype, "end");
      const resolveFileUrl = vi.spyOn(media, "resolveFileUrl").mockImplementation(async () => {
        expect(end).toHaveBeenCalledTimes(1);
        return "https://media.example.test/video";
      });
      expect(await courses.updateUserCourse(env, 40, "owner", { name: "Changed" }))
        .toMatchObject({ course: { videos: [
          { id: 2, file: "https://media.example.test/video" },
          { id: 1, file: "https://media.example.test/video" },
        ] } });
      expect(resolveFileUrl).toHaveBeenCalledTimes(2);
    });
  });

  it.each(["owner", "member", "public"])("does not aggregate unused tags for the Web %s view", async (role) => {
    const query = vi.spyOn(pg.Client.prototype, "query");
    const course = role === "public"
      ? await courses.getSharedCourse(env, "shared-course")
      : await courses.getCourse(env, 10, role);
    expect(course).toMatchObject({ id: 10, video_count: 2, access_role: role, videos: [
      { id: 1, title: "First", order: 3, file: "/api/media/videos/example.mp4" },
      { id: 2, title: "Second", order: 3, file: "/api/media/videos/example.mp4" },
    ] });
    expect(statements(query.mock.calls)).not.toContain("video_tags");
  });

  it("does not aggregate unused tags in the Web update response", async () => {
    const query = vi.spyOn(pg.Client.prototype, "query");
    expect(await courses.updateUserCourse(env, 10, "owner", { description: "Updated" }))
      .toMatchObject({ course: { description: "Updated", videos: [{ id: 1 }, { id: 2 }] } });
    expect(statements(query.mock.calls)).not.toContain("video_tags");
  });

  it("preserves tags and stable member pagination in MCP without generating file URLs", async () => {
    const resolveFileUrl = vi.spyOn(media, "resolveFileUrl");
    const context = { env: { ...env, USE_S3_STORAGE: "true" }, userId: "member", canWrite: false };
    expect(await callMcpTool("get_course", { course_id: 10, video_limit: 1 }, context)).toMatchObject({
      course: { access_role: "member", videos: [{ id: 1, tags: [
        { id: 2, name: "A tag", color: "red" }, { id: 1, name: "Z tag", color: "blue" },
      ] }] },
      videos_meta: { total: 2, next_offset: 1, has_more: true },
    });
    expect(await callMcpTool("get_course", { course_id: 10, video_limit: 1, video_offset: 1 }, context))
      .toMatchObject({ course: { videos: [{ id: 2, tags: [{ id: 1 }] }] }, videos_meta: { has_more: false } });
    expect(resolveFileUrl).not.toHaveBeenCalled();
  });

  it("does not generate discarded file URLs when an MCP creation is retried after adding videos", async () => {
    const resolveFileUrl = vi.spyOn(media, "resolveFileUrl");
    const context = { env: { ...env, USE_S3_STORAGE: "true" }, userId: "creator", canWrite: true };
    const args = { name: "Created", idempotency_key: "create-once" };
    const first = await callMcpTool("create_course", args, context);
    const courseId = (first.course as { id: number }).id;
    await admin.query("INSERT INTO video_course_members (course_id, video_id) VALUES ($1, 4)", [courseId]);
    const second = await callMcpTool("create_course", args, context);
    expect(second).toMatchObject({ reused: true, course: { id: courseId, videos: [{ id: 4, tags: [{ id: 4 }] }] } });
    expect(JSON.stringify(second)).not.toContain("example.mp4");
    expect(resolveFileUrl).not.toHaveBeenCalled();
  });

  it.each([
    { courseId: 30, offset: 0, count: 0 },
    { courseId: 10, offset: 2, count: 2 },
    { courseId: 10, offset: 100, count: 2 },
  ])("skips the empty member query for %j", async ({ courseId, offset, count }) => {
    const query = vi.spyOn(pg.Client.prototype, "query");
    expect(await getCourseDetail(env, courseId, "owner", { videoLimit: 1, videoOffset: offset }))
      .toMatchObject({ video_count: count, videos: [] });
    expect(query).toHaveBeenCalledTimes(1);
    query.mockClear();
    expect(await getCourseInfo(env, courseId, "owner", {
      videoLimit: 1, videoOffset: offset,
      courseDescriptionLimit: COURSE_DESCRIPTION_LIMIT, videoDescriptionLimit: VIDEO_DESCRIPTION_LIMIT,
    }))
      .toMatchObject({ video_count: count, videos: [] });
    expect(query).toHaveBeenCalledTimes(1);
  });

  it.each([
    { userId: "missing", offset: 0, count: 0 },
    { userId: "owner", offset: 2, count: 2 },
    { userId: "member", offset: 100, count: 1 },
  ])("skips fetching an empty course list for %j", async ({ userId, offset, count }) => {
    const query = vi.spyOn(pg.Client.prototype, "query");
    expect(await listCoursesPage(env, userId, 10, offset)).toEqual({ count, results: [] });
    expect(query).toHaveBeenCalledTimes(1);
  });

  it("preserves full repository reads, tag-detail correlation and access restrictions", async () => {
    expect(await getCourseDetail(env, 10, "owner")).toMatchObject({ videos: [
      { id: 1, tags: [{ id: 2 }, { id: 1 }] }, { id: 2, tags: [{ id: 1 }] },
    ] });
    expect(await getCourseDetailByShareSlug(env, "shared-course")).toMatchObject({ access_role: "public", videos: [
      { id: 1, tags: [{ id: 2 }, { id: 1 }] }, { id: 2, tags: [{ id: 1 }] },
    ] });
    expect(await getTagDetail(env, 1, "owner")).toMatchObject({ video_count: 2, videos: [
      { id: 1, tags: [{ id: 2 }, { id: 1 }] }, { id: 2, tags: [{ id: 1 }] },
    ] });
    expect(await courses.getCourse(env, 10, "outsider")).toBeNull();
    expect(await courses.getSharedCourse(env, "invalid")).toBeNull();
    expect(await courses.updateUserCourse(env, 10, "member", { name: "Denied" })).toEqual({ notFound: true });
    expect(await getCourseInfo(env, 10, "member", {
      videoLimit: 1, videoOffset: 0,
      courseDescriptionLimit: COURSE_DESCRIPTION_LIMIT, videoDescriptionLimit: VIDEO_DESCRIPTION_LIMIT,
    })).toBeNull();
    expect(await listCoursesPage(env, "member", 10, 0)).toMatchObject({ count: 1, results: [{ id: 10, access_role: "member", video_count: 2 }] });
  });
});
