import pg from "pg";
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { acceptInvitation, declineInvitation, inviteCourseMembers, previewCourseInvitation } from "../src/features/course-memberships/service";
import { hashInvitationToken } from "../src/lib/course-invitations";
import { listCourseParticipants } from "../src/repositories/course-invitation-repository";
import type { Bindings } from "../src/types/bindings";

const databaseUrl = process.env.QUOTA_TEST_DATABASE_URL;
const now = new Date("2026-09-23T12:00:00.000Z");

(databaseUrl ? describe : describe.skip)("invitation reads on PostgreSQL", () => {
  const schema = `invitation_reads_${crypto.randomUUID().replaceAll("-", "")}`;
  let admin: pg.Client;
  let env: Bindings;

  beforeAll(async () => {
    admin = new pg.Client({ connectionString: databaseUrl });
    await admin.connect();
    const url = new URL(databaseUrl!);
    url.searchParams.set("options", `-c search_path=${schema}`);
    env = { HYPERDRIVE: { connectionString: url.toString() } } as Bindings;
  });
  beforeEach(async () => {
    await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
    await admin.query(`CREATE SCHEMA "${schema}"`);
    await admin.query(`SET search_path TO "${schema}"`);
    await admin.query(`
      CREATE TABLE users (id text PRIMARY KEY, name text NOT NULL, username text NOT NULL,
        email text NOT NULL, email_verified boolean NOT NULL DEFAULT true);
      CREATE TABLE video_courses (id integer PRIMARY KEY, user_id text REFERENCES users, name text NOT NULL);
      CREATE TABLE video_course_invitations (
        id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
        course_id integer REFERENCES video_courses, invited_by_user_id text REFERENCES users,
        email text NOT NULL, token_hash text NOT NULL UNIQUE,
        status text NOT NULL DEFAULT 'pending', delivery_status text NOT NULL DEFAULT 'sent',
        expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT '2026-09-01',
        updated_at timestamptz NOT NULL DEFAULT '2026-09-01', last_sent_at timestamptz,
        send_attempts integer NOT NULL DEFAULT 1, accepted_by_user_id text, accepted_at timestamptz,
        last_error text
      );
      CREATE UNIQUE INDEX pending_email ON video_course_invitations(course_id, email) WHERE status = 'pending';
      CREATE TABLE video_course_memberships (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        course_id integer REFERENCES video_courses, user_id text REFERENCES users,
        invitation_id integer REFERENCES video_course_invitations, joined_at timestamptz NOT NULL,
        UNIQUE (course_id, user_id)
      );
      CREATE TABLE external_tasks (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        kind text NOT NULL, payload jsonb NOT NULL, dedupe_key text NOT NULL UNIQUE,
        attempts integer NOT NULL DEFAULT 0, available_at timestamptz DEFAULT now(),
        locked_at timestamptz, completed_at timestamptz, effect_applied_at timestamptz,
        dead_at timestamptz, last_error text NOT NULL DEFAULT '',
        created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
      INSERT INTO users VALUES ('owner', 'Teacher', 'teacher', 'teacher@example.com'),
        ('recipient', 'Student', 'student', 'student@example.com'),
        ('outsider', 'Other', 'other', 'other@example.com');
      INSERT INTO video_courses VALUES (10, 'owner', 'Course'), (20, 'outsider', 'Private course');
      INSERT INTO video_course_memberships (course_id, user_id, joined_at) VALUES (10, 'recipient', '2026-09-02');
    `);
    await admin.query(`INSERT INTO video_course_invitations
      (id, course_id, invited_by_user_id, email, token_hash, expires_at)
      VALUES (1, 10, 'owner', 'student@example.com', $1, $2),
             (2, 20, 'outsider', 'private@example.com', $3, '2099-01-01')`,
    [await hashInvitationToken("old-token"), now, await hashInvitationToken("private-token")]);
  });
  afterEach(() => vi.restoreAllMocks());
  afterAll(async () => {
    try { await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); }
    finally { await admin.end(); }
  });

  async function snapshot() {
    return (await admin.query("SELECT * FROM video_course_invitations ORDER BY id")).rows;
  }

  it.each([
    ["pending", -1, "expired"], ["pending", 0, "expired"], ["pending", 1, "pending"],
    ["accepted", -1, "accepted"], ["declined", -1, "declined"],
    ["revoked", -1, "revoked"], ["expired", 1, "expired"],
  ])("previews %s at offset %i as %s with one read and no writes", async (status, offset, expected) => {
    const expiresAt = new Date(now.getTime() + Number(offset));
    await admin.query("UPDATE video_course_invitations SET status = $1, expires_at = $2 WHERE id = 1", [status, expiresAt]);
    const before = await snapshot();
    const query = vi.spyOn(pg.Client.prototype, "query");
    const connect = vi.spyOn(pg.Client.prototype, "connect");
    await expect(previewCourseInvitation(env, "old-token", now)).resolves.toEqual({
      course_id: 10, course_name: "Course", inviter_name: "Teacher",
      email_hint: "s*****t@example.com", status: expected, expires_at: expiresAt.toISOString(),
    });
    expect(connect).toHaveBeenCalledTimes(1);
    expect(query).toHaveBeenCalledTimes(1);
    vi.restoreAllMocks();
    expect(await snapshot()).toEqual(before);
  });

  it("does not expire a renewed invitation after previewing an older token", async () => {
    const end = pg.Client.prototype.end;
    let renewed = false;
    const newHash = await hashInvitationToken("new-token");
    vi.spyOn(pg.Client.prototype, "end").mockImplementation(async function (this: pg.Client) {
      await end.call(this);
      if (!renewed) {
        renewed = true;
        await admin.query("UPDATE video_course_invitations SET token_hash = $1, expires_at = '2099-01-01' WHERE id = 1", [newHash]);
      }
    });
    await expect(previewCourseInvitation(env, "old-token", now)).resolves.toMatchObject({ status: "expired" });
    expect((await snapshot())[0]).toMatchObject({ status: "pending", token_hash: newHash });
    await expect(previewCourseInvitation(env, "new-token", now)).resolves.toMatchObject({ status: "pending" });
    await expect(previewCourseInvitation(env, "old-token", now)).resolves.toBeNull();
  });

  it("lists participants and effective expiry without changing stored invitations", async () => {
    await admin.query("UPDATE video_course_invitations SET expires_at = '2020-01-01' WHERE id = 1");
    await admin.query(`INSERT INTO video_course_invitations
      (id, course_id, invited_by_user_id, email, token_hash, status, expires_at, created_at)
      VALUES (3, 10, 'owner', 'accepted@example.com', 'accepted-token', 'accepted', '2020-01-01', '2026-09-03'),
             (4, 10, 'owner', 'pending@example.com', 'pending-token', 'pending', '2099-01-01', '2026-09-04')`);
    const before = await snapshot();
    const query = vi.spyOn(pg.Client.prototype, "query");
    const result = await listCourseParticipants(env, 10, "owner");
    expect(query).toHaveBeenCalledTimes(3);
    vi.restoreAllMocks();
    expect(result).toMatchObject({
      invitations: [{ id: 4, status: "pending" }, { id: 3, status: "accepted" }, { id: 1, status: "expired" }],
      members: [{ user_id: "recipient", username: "student", email: "student@example.com" }],
    });
    expect(await snapshot()).toEqual(before);
  });

  it("allows both reads on a read-only connection even for expired invitations", async () => {
    await admin.query("UPDATE video_course_invitations SET expires_at = '2020-01-01' WHERE id = 1");
    const url = new URL(env.HYPERDRIVE.connectionString);
    url.searchParams.set("options", `-c search_path=${schema} -c default_transaction_read_only=on`);
    const readOnly = { HYPERDRIVE: { connectionString: url.toString() } } as Bindings;
    await expect(previewCourseInvitation(readOnly, "old-token", now)).resolves.toMatchObject({ status: "expired" });
    await expect(listCourseParticipants(readOnly, 10, "owner")).resolves.toMatchObject({ invitations: [{ status: "expired" }] });
  });

  it.each([20, 99])("does not expose participants of an unowned or missing course %i", async courseId => {
    const before = await snapshot();
    await expect(listCourseParticipants(env, courseId, "owner")).resolves.toEqual({ notFound: true });
    expect(await snapshot()).toEqual(before);
  });

  it.each([acceptInvitation, declineInvitation])("still rejects expired invitations when deciding (%#)", async decide => {
    await expect(previewCourseInvitation(env, "old-token", now)).resolves.toMatchObject({ status: "expired" });
    await expect(decide(env, "old-token", "recipient", now)).resolves.toEqual({ expired: true });
    expect((await snapshot())[0].status).toBe("expired");
  });

  it("can issue a new invitation after a read-only expired preview", async () => {
    await admin.query("DELETE FROM video_course_memberships WHERE course_id = 10");
    await previewCourseInvitation(env, "old-token", now);
    await expect(inviteCourseMembers(env, 10, "owner", ["student@example.com"], now)).resolves.toMatchObject({
      results: [{ email: "student@example.com", status: "queued" }],
    });
    expect((await admin.query("SELECT status FROM video_course_invitations WHERE course_id = 10 ORDER BY id")).rows)
      .toEqual([{ status: "expired" }, { status: "pending" }]);
    expect((await admin.query("SELECT count(*)::int AS count FROM external_tasks")).rows[0].count).toBe(1);
  });
});
