import { readFileSync } from "node:fs";
import pg from "pg";
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { editCreateEdge, editDeleteConcept, editDeleteEdge, editUpdateEdge, editUpdateLearningObject } from "../src/features/plog/service";
import { createConcept, createEdge, PlogConflictError, PlogEditError, updateEdge } from "../src/repositories/plog-repository";
import type { Bindings } from "../src/types/bindings";

const databaseUrl = process.env.QUOTA_TEST_DATABASE_URL;
const fixture = readFileSync(new URL("./fixtures/video-deletion.sql", import.meta.url), "utf8");

(databaseUrl ? describe : describe.skip)("PLOG edge edits on PostgreSQL", () => {
  const schema = `plog_edges_${crypto.randomUUID().replaceAll("-", "")}`;
  let admin: pg.Client;
  let env: Bindings;

  beforeAll(async () => {
    admin = new pg.Client({ connectionString: databaseUrl });
    await admin.connect();
    const url = new URL(databaseUrl!);
    url.searchParams.set("options", `-c search_path=${schema}`);
    env = { HYPERDRIVE: { connectionString: url.toString() } } as Bindings;
  });
  beforeEach(async () => {
    await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
    await admin.query(`CREATE SCHEMA "${schema}"`);
    await admin.query(`SET search_path TO "${schema}"`);
    await admin.query(fixture);
    await admin.query(`
      ALTER TABLE plog_build_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 100);
      ALTER TABLE plog_build_jobs ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(), ADD COLUMN finished_at timestamptz;
      INSERT INTO plog_concepts (id, video_id, label) VALUES (3, 10, 'Target'), (4, 10, 'Other');
      UPDATE plog_edges SET target_id = 3, edge_type = 'analogy_for' WHERE id = 1;
    `);
  });
  afterEach(async () => {
    vi.restoreAllMocks();
    await admin.query("ROLLBACK");
  });
  afterAll(async () => {
    try { await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); }
    finally { await admin.end(); }
  });

  async function snapshot() {
    const result: Record<string, unknown[]> = {};
    for (const table of ["plog_edges", "plog_concepts", "plog_build_jobs", "plog_learning_objects"]) {
      result[table] = (await admin.query(`SELECT * FROM ${table} ORDER BY id`)).rows;
    }
    return result;
  }

  const input = { sourceId: 1, targetId: 3, edgeType: "example_of", quote: "A quote" };

  function observeGraphLock() {
    const reached = Promise.withResolvers<void>();
    const originalQuery = pg.Client.prototype.query;
    vi.spyOn(pg.Client.prototype, "query").mockImplementation(function (this: pg.Client, ...args: Parameters<typeof originalQuery>) {
      const config = args[0];
      const sql = typeof config === "string" ? config : (config as { text: string }).text;
      if (this !== admin && sql.includes("FROM videos") && sql.includes("FOR UPDATE")) reached.resolve();
      return Reflect.apply(originalQuery, this, args);
    } as typeof originalQuery);
    return reached.promise;
  }

  it.each(["create", "update"])("uses one connection for %s and returns labels and provenance", async operation => {
    const connect = vi.spyOn(pg.Client.prototype, "connect");
    const result = operation === "create"
      ? await editCreateEdge(env, 10, input)
      : await editUpdateEdge(env, 10, 1, input);
    expect(result).toMatchObject({ ok: true, value: {
      source_id: 1, source_label: "", target_id: 3, target_label: "Target",
      edge_type: "example_of", quote: "A quote", provenance: "edited",
    } });
    expect(connect).toHaveBeenCalledTimes(1);
  });

  const invalidEndpoints = [
    { sourceId: 2, targetId: 3, message: "source_id does not exist for this video" },
    { sourceId: 99, targetId: 3, message: "source_id does not exist for this video" },
    { sourceId: 1, targetId: 2, message: "target_id does not exist for this video" },
    { sourceId: 1, targetId: 99, message: "target_id does not exist for this video" },
    { sourceId: 1, targetId: 1, message: "source_id and target_id must differ" },
  ];
  describe.each(["create", "update"])("%s endpoint validation", operation => {
    it.each(invalidEndpoints)("rejects $sourceId → $targetId inside the write transaction", async ({ message, ...endpoints }) => {
      const before = await snapshot();
      const params = { videoId: 10, ...input, ...endpoints };
      await expect(operation === "create" ? createEdge(env, params) : updateEdge(env, { ...params, edgeId: 1 }))
        .rejects.toThrow(new PlogEditError(message));
      expect(await snapshot()).toEqual(before);
    });
  });

  it("checks a partial update against the edge after acquiring the graph lock", async () => {
    await admin.query("BEGIN");
    await admin.query("SELECT 1 FROM videos WHERE id = 10 FOR UPDATE");
    const reachedLock = observeGraphLock();
    const pending = editUpdateEdge(env, 10, 1, { sourceId: 4 });
    await reachedLock;
    await admin.query("UPDATE plog_edges SET target_id = 4 WHERE id = 1");
    await admin.query("COMMIT");
    await expect(pending).resolves.toEqual({ ok: false, status: 400, message: "source_id and target_id must differ" });
    expect((await admin.query("SELECT source_id, target_id FROM plog_edges WHERE id = 1")).rows)
      .toEqual([{ source_id: 1, target_id: 4 }]);
  });

  it("returns a validation error if an endpoint is deleted while creation waits for the graph lock", async () => {
    await admin.query("BEGIN");
    await admin.query("SELECT 1 FROM videos WHERE id = 10 FOR UPDATE");
    const reachedLock = observeGraphLock();
    // Observe rejection immediately so the pre-fix foreign-key error is not unhandled.
    const pending = editCreateEdge(env, 10, { ...input, targetId: 4 }).catch(error => error);
    await reachedLock;
    await admin.query("DELETE FROM plog_concepts WHERE id = 4");
    await admin.query("COMMIT");
    await expect(pending).resolves.toEqual({ ok: false, status: 400, message: "target_id does not exist for this video" });
    expect((await admin.query("SELECT count(*)::int AS n FROM plog_edges WHERE video_id = 10")).rows[0].n).toBe(1);
  });

  it.each(["quote", "empty"])("does not scan the graph to apply a %s patch", async patchKind => {
    await admin.query("UPDATE plog_edges SET edge_type = 'presentation_order' WHERE id = 1");
    const query = vi.spyOn(pg.Client.prototype, "query");
    const connect = vi.spyOn(pg.Client.prototype, "connect");
    await expect(editUpdateEdge(env, 10, 1, patchKind === "quote" ? { quote: "New quote" } : {}))
      .resolves.toMatchObject({ ok: true, value: { quote: patchKind === "quote" ? "New quote" : "" } });
    const sqls = query.mock.calls.map(([q]) => (typeof q === "string" ? q : q.text).replaceAll('"', ""));
    expect(sqls.some(sql => sql.includes("from plog_edges") && sql.includes("edge_type in"))).toBe(false);
    expect(connect).toHaveBeenCalledTimes(1);
    expect(query).toHaveBeenCalledTimes(patchKind === "quote" ? 6 : 5);
  });

  it.each([2, 99])("does not modify missing or out-of-video edge %i", async edgeId => {
    const before = await snapshot();
    await expect(editUpdateEdge(env, 10, edgeId, input)).resolves.toEqual({ ok: false, status: 404, message: "Edge not found." });
    expect(await snapshot()).toEqual(before);
  });

  it.each(["pending", "running"])("maps all edits during a %s rebuild to validation errors", async status => {
    await admin.query("UPDATE plog_build_jobs SET status = $1 WHERE video_id = 10", [status]);
    const before = await snapshot();
    for (const run of [
      () => editCreateEdge(env, 10, input),
      () => editUpdateEdge(env, 10, 1, input),
      () => editDeleteEdge(env, 10, 1),
      () => editDeleteConcept(env, 10, 1),
      () => editUpdateLearningObject(env, 10, 1, { openingQuestion: "New question" }),
    ]) {
      await expect(run()).resolves.toEqual({ ok: false, status: 400, message: "Cannot edit graph while a rebuild is in progress." });
    }
    expect(await snapshot()).toEqual(before);
  });

  it.each(["create", "update"])("rejects an invalid relationship type on %s", async operation => {
    const before = await snapshot();
    const invalid = { ...input, edgeType: "invalid" };
    await expect(operation === "create" ? editCreateEdge(env, 10, invalid) : editUpdateEdge(env, 10, 1, invalid))
      .resolves.toEqual({ ok: false, status: 400, message: "Invalid edge_type: invalid" });
    expect(await snapshot()).toEqual(before);
  });

  it.each(["prerequisite_of", "builds_on", "presentation_order"])("prevents cycles across %s creation and updates", async edgeType => {
    await admin.query("UPDATE plog_edges SET edge_type = 'presentation_order' WHERE id = 1");
    await admin.query("INSERT INTO plog_edges (id, video_id, source_id, target_id, edge_type) VALUES (5, 10, 3, 4, 'builds_on')");
    const before = await snapshot();
    for (const result of [
      await editCreateEdge(env, 10, { ...input, sourceId: 4, targetId: 1, edgeType }),
      await editUpdateEdge(env, 10, 1, { sourceId: 4, edgeType }),
    ]) {
      expect(result).toEqual({ ok: false, status: 400, message: "Ordering edges must form a DAG (cycle detected)." });
    }
    expect(await snapshot()).toEqual(before);
  });

  it("allows reversing the edited ordering edge when it creates no cycle", async () => {
    await admin.query("UPDATE plog_edges SET edge_type = 'presentation_order' WHERE id = 1");
    await expect(editUpdateEdge(env, 10, 1, { sourceId: 3, targetId: 1 }))
      .resolves.toMatchObject({ ok: true, value: { source_id: 3, source_label: "Target", target_id: 1, target_label: "" } });
  });

  it("serializes opposite ordering edges so concurrent requests cannot create a cycle", async () => {
    const results = await Promise.all([
      editCreateEdge(env, 10, { ...input, edgeType: "presentation_order" }),
      editCreateEdge(env, 10, { ...input, sourceId: 3, targetId: 1, edgeType: "builds_on" }),
    ]);
    expect(results.filter(result => result.ok)).toHaveLength(1);
    expect(results.filter(result => !result.ok)).toEqual([
      { ok: false, status: 400, message: "Ordering edges must form a DAG (cycle detected)." },
    ]);
  });

  it.each(["failed", "missing"])("keeps a %s build unchanged when edge creation fails", async status => {
    if (status === "missing") await admin.query("DELETE FROM plog_build_jobs WHERE video_id = 10");
    else await admin.query("UPDATE plog_build_jobs SET status = 'failed' WHERE video_id = 10");
    const before = await snapshot();
    await expect(editCreateEdge(env, 10, { ...input, edgeType: "analogy_for" }))
      .resolves.toEqual({ ok: false, status: 400, message: "This edge already exists." });
    expect(await snapshot()).toEqual(before);
  });

  it.each(["failed", "missing"])("makes a %s build ready in the successful creation transaction", async status => {
    if (status === "missing") await admin.query("DELETE FROM plog_build_jobs WHERE video_id = 10");
    else await admin.query("UPDATE plog_build_jobs SET status = 'failed' WHERE video_id = 10");
    await expect(editCreateEdge(env, 10, input)).resolves.toMatchObject({ ok: true });
    expect((await admin.query("SELECT status FROM plog_build_jobs WHERE video_id = 10 ORDER BY id DESC")).rows)
      .toEqual(status === "failed" ? [{ status: "ready" }, { status: "failed" }] : [{ status: "ready" }]);
  });

  it("commits the ready job with a new concept and its learning object", async () => {
    await admin.query("DELETE FROM plog_build_jobs WHERE video_id = 10");
    const connect = vi.spyOn(pg.Client.prototype, "connect");
    await expect(createConcept(env, { videoId: 10, label: "New", nodeType: "object", introSec: 0, sourceQuote: "", embedding: [] }))
      .resolves.toMatchObject({ label: "New", hint_ladder: [] });
    expect(connect).toHaveBeenCalledTimes(1);
    expect((await admin.query("SELECT status FROM plog_build_jobs WHERE video_id = 10")).rows).toEqual([{ status: "ready" }]);
  });

  it("rolls back the ready job when a concept cannot be created", async () => {
    await admin.query("DELETE FROM plog_build_jobs WHERE video_id = 10");
    const before = await snapshot();
    await expect(createConcept(env, { videoId: 10, label: "Target", nodeType: "object", introSec: 0, sourceQuote: "", embedding: [] }))
      .rejects.toBeInstanceOf(PlogConflictError);
    expect(await snapshot()).toEqual(before);
  });
});
