import pg from "pg";
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { createTag, EMPTY_NAME_MESSAGE, getTagDetail, INVALID_COLOR_MESSAGE, listTagsPage, updateTag } from "../src/repositories/tag-repository";
import * as media from "../src/integrations/media";
import type { Bindings } from "../src/types/bindings";

const databaseUrl = process.env.QUOTA_TEST_DATABASE_URL;

(databaseUrl ? describe : describe.skip)("tag reads and metadata updates on PostgreSQL", () => {
  const schema = `tag_reads_${crypto.randomUUID().replaceAll("-", "")}`;
  let admin: pg.Client;
  let env: Bindings;

  beforeAll(async () => {
    admin = new pg.Client({ connectionString: databaseUrl });
    await admin.connect();
    await admin.query(`
      CREATE SCHEMA "${schema}";
      SET search_path TO "${schema}";
      CREATE TABLE tags (
        id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
        user_id text NOT NULL, name text NOT NULL, color text NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, name)
      );
      CREATE TABLE videos (
        id bigint PRIMARY KEY, user_id text NOT NULL, title text NOT NULL,
        description text NOT NULL DEFAULT '', file text NOT NULL DEFAULT 'videos/example.mp4',
        uploaded_at timestamptz NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'completed',
        source_type text NOT NULL DEFAULT 'uploaded', source_url text NOT NULL DEFAULT '',
        youtube_video_id text NOT NULL DEFAULT ''
      );
      CREATE TABLE video_tags (
        id bigint PRIMARY KEY, video_id bigint NOT NULL REFERENCES videos ON DELETE CASCADE,
        tag_id bigint NOT NULL REFERENCES tags ON DELETE CASCADE, UNIQUE(video_id, tag_id)
      );
      INSERT INTO videos (id, user_id, title) VALUES
        (1, 'owner', 'First'), (2, 'owner', 'Second'), (3, 'other', 'Private');
    `);
    const url = new URL(databaseUrl!);
    url.searchParams.set("options", `-c search_path=${schema}`);
    url.searchParams.set("application_name", schema);
    env = { HYPERDRIVE: { connectionString: url.toString() } } as Bindings;
  });
  beforeEach(async () => {
    await admin.query(`
      TRUNCATE tags CASCADE;
      INSERT INTO tags (id, user_id, name, color, created_at) VALUES
        (1, 'owner', 'Z tag', '#legacy', '2026-09-23T09:00:00+09:00'),
        (2, 'owner', 'A tag', 'red', '2026-09-23T09:00:00+09:00'),
        (3, 'other', 'Private', 'green', '2026-09-23T09:00:00+09:00'),
        (4, 'owner', 'Empty', 'blue', '2026-09-23T09:00:00+09:00');
      INSERT INTO video_tags VALUES (20, 1, 1), (10, 2, 1), (30, 1, 2), (40, 3, 3);
    `);
  });
  afterEach(() => vi.restoreAllMocks());
  afterAll(async () => {
    try { await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); }
    finally { await admin.end(); }
  });

  function statements(calls: unknown[][]) {
    return calls.map(([config]) => typeof config === "string" ? config : (config as pg.QueryConfig).text);
  }

  it.each([
    { fields: { name: " Renamed " }, name: "Renamed", color: "#legacy" },
    { fields: { color: "blue" }, name: "Z tag", color: "blue" },
    { fields: { name: "Both", color: "red" }, name: "Both", color: "red" },
    { fields: {}, name: "Z tag", color: "#legacy" },
  ])("returns metadata without reading or signing attached videos for $fields", async ({ fields, name, color }) => {
    const query = vi.spyOn(pg.Client.prototype, "query");
    const resolveFileUrl = vi.spyOn(media, "resolveFileUrl").mockResolvedValue("signed-url");
    expect(await updateTag({ ...env, USE_S3_STORAGE: "true" }, 1, "owner", fields)).toEqual({ tag: {
      id: 1, name, color, created_at: "2026-09-23T00:00:00.000Z", video_count: 2,
    } });
    expect(resolveFileUrl).not.toHaveBeenCalled();
    const sql = statements(query.mock.calls);
    expect(sql.join("\n")).not.toContain('join "videos"');
    expect(sql.join("\n")).not.toContain("jsonb_agg");
    expect(sql).toHaveLength(1);
  });

  it("preserves alphabetical pagination, ownership and video counts", async () => {
    expect(await listTagsPage(env, "owner", 2, 0)).toEqual({ count: 3, results: [
      { id: 2, name: "A tag", color: "red", created_at: "2026-09-23T00:00:00.000Z", video_count: 1 },
      { id: 4, name: "Empty", color: "blue", created_at: "2026-09-23T00:00:00.000Z", video_count: 0 },
    ] });
    expect(await listTagsPage(env, "owner", 2, 2)).toMatchObject({ count: 3, results: [{ id: 1, video_count: 2 }] });
  });

  it.each([
    { userId: "missing", offset: 0, count: 0 },
    { userId: "owner", offset: 3, count: 3 },
    { userId: "other", offset: 100, count: 1 },
  ])("skips the empty page query for %j", async ({ userId, offset, count }) => {
    const query = vi.spyOn(pg.Client.prototype, "query");
    expect(await listTagsPage(env, userId, 10, offset)).toEqual({ count, results: [] });
    expect(query).toHaveBeenCalledTimes(1);
  });

  it("keeps full tag details in attachment order without counting the same videos separately", async () => {
    const query = vi.spyOn(pg.Client.prototype, "query");
    const resolveFileUrl = vi.spyOn(media, "resolveFileUrl").mockResolvedValue("signed-url");
    expect(await getTagDetail(env, 1, "owner")).toEqual({
      id: 1, name: "Z tag", color: "#legacy", created_at: "2026-09-23T00:00:00.000Z", video_count: 2,
      videos: [
        expect.objectContaining({ id: 2, file: "signed-url", tags: [{ id: 1, name: "Z tag", color: "#legacy" }] }),
        expect.objectContaining({ id: 1, file: "signed-url", tags: [
          { id: 2, name: "A tag", color: "red" }, { id: 1, name: "Z tag", color: "#legacy" },
        ] }),
      ],
    });
    expect(query).toHaveBeenCalledTimes(2);
    expect(statements(query.mock.calls)[0]).not.toContain("video_tags");
    expect(resolveFileUrl).toHaveBeenCalledTimes(2);
  });

  it("keeps empty detail and creation responses consistent", async () => {
    expect(await getTagDetail(env, 4, "owner")).toEqual({
      id: 4, name: "Empty", color: "blue", created_at: "2026-09-23T00:00:00.000Z", video_count: 0, videos: [],
    });
    const created = await createTag(env, "owner", "Created", "green");
    expect(created).toEqual({ id: expect.any(Number), name: "Created", color: "green", video_count: 0, created_at: expect.any(String) });
    expect(new Date(created.created_at).toISOString()).toBe(created.created_at);
    expect(await getTagDetail(env, created.id, "owner")).toEqual({ ...created, videos: [] });
  });

  it.each([{ id: 3, userId: "owner" }, { id: 99, userId: "owner" }])("does not read videos for inaccessible tags %j", async ({ id, userId }) => {
    const query = vi.spyOn(pg.Client.prototype, "query");
    expect(await getTagDetail(env, id, userId)).toBeNull();
    expect(query).toHaveBeenCalledTimes(1);
  });

  it.each([
    { fields: { name: " ", color: "blue" }, error: EMPTY_NAME_MESSAGE },
    { fields: { name: "Edited", color: "invalid" }, error: INVALID_COLOR_MESSAGE },
    { fields: { name: " ", color: "invalid" }, error: EMPTY_NAME_MESSAGE },
  ])("keeps validation atomic and behind ownership for $fields", async ({ fields, error }) => {
    const before = (await admin.query("SELECT *, xmin::text AS version FROM tags ORDER BY id")).rows;
    const query = vi.spyOn(pg.Client.prototype, "query");
    expect(await updateTag(env, 1, "owner", fields)).toEqual({ error });
    expect(query).toHaveBeenCalledTimes(1);
    expect(await updateTag(env, 3, "owner", fields)).toEqual({ notFound: true });
    expect(await updateTag(env, 99, "owner", fields)).toEqual({ notFound: true });
    expect(query).toHaveBeenCalledTimes(3);
    query.mockRestore();
    expect((await admin.query("SELECT *, xmin::text AS version FROM tags ORDER BY id")).rows).toEqual(before);
  });

  it("does not rewrite a tag for an empty patch", async () => {
    const before = (await admin.query("SELECT *, xmin::text AS version FROM tags WHERE id = 1")).rows;
    expect(await updateTag(env, 1, "owner", {})).toMatchObject({ tag: { name: "Z tag", color: "#legacy" } });
    expect((await admin.query("SELECT *, xmin::text AS version FROM tags WHERE id = 1")).rows).toEqual(before);
  });

  it("preserves independent name and color updates when they overlap", async () => {
    await Promise.all([
      updateTag(env, 1, "owner", { name: "Edited" }),
      updateTag(env, 1, "owner", { color: "blue" }),
    ]);
    expect((await admin.query("SELECT name, color FROM tags WHERE id = 1")).rows)
      .toEqual([{ name: "Edited", color: "blue" }]);
  });

  it.each(["delete", "transfer"])("returns notFound when a concurrent %s wins the tag lock", async operation => {
    const writer = new pg.Client({ connectionString: env.HYPERDRIVE.connectionString });
    await writer.connect();
    let update: Promise<unknown> | undefined;
    try {
      await writer.query("BEGIN");
      await writer.query(operation === "delete"
        ? "DELETE FROM tags WHERE id = 1"
        : "UPDATE tags SET user_id = 'other' WHERE id = 1");
      update = updateTag(env, 1, "owner", { name: "Changed" }).catch((error: unknown) => error);
      await vi.waitFor(async () => {
        const result = await admin.query("SELECT 1 FROM pg_stat_activity WHERE application_name = $1 AND wait_event_type = 'Lock'", [schema]);
        expect(result.rowCount).toBe(1);
      });
      await writer.query("COMMIT");
      expect(await update).toEqual({ notFound: true });
      if (operation === "transfer") {
        expect((await admin.query("SELECT user_id, name FROM tags WHERE id = 1")).rows)
          .toEqual([{ user_id: "other", name: "Z tag" }]);
      }
    } finally {
      await writer.query("ROLLBACK");
      await update;
      await writer.end();
    }
  });
});
