/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WebEnv worker/env.d.ts` (hash: dc7d819705484691dee98f754cb7d97b)
interface __BaseEnv_WebEnv {
	ASSETS: Fetcher;
	ENVIRONMENT: "production" | "development";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		ASSETS: Fetcher;
		ENVIRONMENT: "production";
	}
	interface Env extends __BaseEnv_WebEnv {}
}
interface WebEnv extends __BaseEnv_WebEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
declare module "*/_headers" {
	const value: string;
	export default value;
	}