# Generated by Django 5.2.7 on 2025-10-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="encrypted_openai_api_key",
            field=models.TextField(
                blank=True, help_text="Encrypted OpenAI API key", null=True
            ),
        ),
    ]
