# Generated by Django 5.2.7 on 2025-11-22 00:54

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when video was deleted (soft delete for monthly usage tracking)', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=app.models.user_directory_path),
        ),
    ]
