# Generated by Django 5.2.7 on 2025-11-27 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_video_deleted_at_alter_video_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="chat_limit",
        ),
        migrations.RemoveField(
            model_name="user",
            name="video_limit",
        ),
        migrations.RemoveField(
            model_name="user",
            name="whisper_minutes_limit",
        ),
        migrations.RemoveField(
            model_name="video",
            name="deleted_at",
        ),
    ]
