# Generated by Django 5.2.7 on 2025-12-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_limits_and_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="openai_api_key_encrypted",
            field=models.BinaryField(
                blank=True, help_text="Encrypted OpenAI API key", null=True
            ),
        ),
    ]
