# Generated by Django 5.2.7 on 2025-10-27 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Group name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Group description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        help_text="Share token",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order within the group"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="app.videogroup",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="app.video",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "added_at"],
                "unique_together": {("group", "video")},
            },
        ),
        migrations.AddField(
            model_name="videogroup",
            name="videos",
            field=models.ManyToManyField(
                related_name="video_groups_through",
                through="app.VideoGroupMember",
                to="app.video",
            ),
        ),
    ]
