# Generated by Django 5.2.7 on 2025-12-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_add_encrypted_openai_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="video_limit",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Maximum number of videos user can upload. 0 means no uploads allowed, null means unlimited.",
                null=True,
            ),
        ),
    ]
