# Generated by Django 5.2.7 on 2025-12-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_user_video_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="ID from external LMS (e.g., Moodle cm_id, Canvas content_id)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
