# Generated by Django 5.2.7 on 2025-11-03 04:34

from django.db import migrations, models

import app.models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_chatlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                storage=app.models.SafeS3Boto3Storage(),
                upload_to=app.models.user_directory_path,
            ),
        ),
    ]
