# Generated by Django 5.2.7 on 2025-12-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_add_external_id_to_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="duration_minutes",
        ),
    ]
