# Generated by Django 5.2.7 on 2025-12-27 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_video_is_external_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_llm_model",
            field=models.CharField(
                default="gpt-4o-mini",
                help_text="Preferred LLM model for chat (e.g., gpt-4o-mini, gpt-4o, gpt-4-turbo)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_llm_temperature",
            field=models.FloatField(
                default=0.7,
                help_text="Temperature for LLM responses (0.0 to 2.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
    ]
