# Generated by Django 5.2.7 on 2025-11-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlog",
            name="feedback",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad")],
                help_text="回答に対するフィードバック（good/bad）",
                max_length=4,
                null=True,
            ),
        ),
    ]
