# Generated by Django 5.2.7 on 2026-01-03 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_user_preferred_llm_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_llm_temperature",
            field=models.FloatField(
                default=0.0,
                help_text="Temperature for LLM responses (0.0 to 2.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
    ]
