# Generated by Django 5.2.7 on 2025-11-19 02:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_chatlog_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="youtube_url",
            field=models.CharField(
                blank=True, help_text="YouTube video URL", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="chatlog",
            name="feedback",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad")],
                help_text="Feedback on the answer (good/bad)",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="video_limit",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum number of videos a user can keep. Can be changed from the admin panel if needed.",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=app.models.SafeFileSystemStorage(),
                upload_to=app.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="is_external_upload",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is an upload from an external API client (file will be deleted after processing)",
            ),
        ),
    ]
