# Generated by Django 5.2.7 on 2025-11-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chatlog_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='encrypted_openai_api_key',
        ),
        migrations.AddField(
            model_name='video',
            name='duration_minutes',
            field=models.FloatField(blank=True, help_text='Video duration in minutes (for Whisper usage tracking)', null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='feedback',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad')], help_text='Feedback on the answer (good/bad)', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='video_limit',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of videos a user can keep. Can be changed from the admin panel if needed.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_external_upload',
            field=models.BooleanField(default=False, help_text='Whether this is an upload from an external API client (file will be deleted after processing)'),
        ),
    ]
