# Generated by Django 6.0.1 on 2026-01-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_add_tag_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="openai_api_key_encrypted",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_llm_model",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_llm_temperature",
        ),
    ]
