# Generated by Django 5.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_encrypted_openai_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(
                choices=[('FREE', 'Free'), ('PRO', 'Pro')],
                default='FREE',
                help_text='User plan (FREE or PRO)',
                max_length=10,
            ),
        ),
    ]

