# Generated by Django 5.2.7 on 2025-11-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='video_limit',
        ),
    ]
