# Generated by Django 5.2.7 on 2025-11-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_video_limit_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_limit',
            field=models.IntegerField(default=0, help_text='Maximum chat count per month'),
        ),
        migrations.AddField(
            model_name='user',
            name='video_limit',
            field=models.IntegerField(default=0, help_text='Maximum number of videos (all time)'),
        ),
        migrations.AddField(
            model_name='user',
            name='whisper_minutes_limit',
            field=models.FloatField(default=0.0, help_text='Maximum Whisper processing time per month (minutes)'),
        ),
    ]
