# Generated by Django 6.0.2 on 2026-03-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_user_deactivated_at_accountdeletionrequest"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="video",
            name="video_external_id_idx",
        ),
        migrations.RemoveField(
            model_name="video",
            name="external_id",
        ),
    ]
