# Generated by Django 6.0.2 on 2026-02-11 08:47

from django.db import migrations


def create_subscriptions(apps, schema_editor):
    User = apps.get_model("app", "User")
    Subscription = apps.get_model("app", "Subscription")
    for user in User.objects.all():
        Subscription.objects.get_or_create(user=user, defaults={"plan": "free"})


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_user_video_limit_video_file_size_subscription"),
    ]

    operations = [
        migrations.RunPython(create_subscriptions, migrations.RunPython.noop),
    ]
