# Generated by Django 5.2.7 on 2025-11-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_add_user_limit_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
    ]
