# Generated by Django 5.2.7 on 2025-11-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_user_plan_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_limit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='whisper_minutes_limit',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_openai_api_key',
            field=models.TextField(blank=True, help_text='Encrypted OpenAI API key', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='video_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of videos a user can keep. Can be changed from the admin panel if needed.'),
        ),
    ]
