# Generated by Django 6.0.2 on 2026-02-11 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_video_duration_seconds_alter_chatlog_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('processing_minutes', 'Processing Minutes')], db_index=True, max_length=30)),
                ('amount', models.FloatField(help_text='Amount consumed (e.g. minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, help_text='Source video (nullable after deletion)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.video')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'resource', 'created_at'], name='app_usagere_user_id_fefe03_idx')],
            },
        ),
    ]
