# Generated by Django 6.0.2 on 2026-03-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_userapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapikey",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("restricted", "Restricted"),
                    ("read_only", "Read Only"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
