# Generated by Django 6.0.3 on 2026-03-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_enable_pgvector_and_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('pending', 'Pending'), ('processing', 'Processing'), ('indexing', 'Indexing'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='pending', max_length=20),
        ),
    ]
