# Generated by Django 6.0.3 on 2026-03-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openai_api_key_encrypted',
            field=models.BinaryField(blank=True, help_text='Encrypted OpenAI API key', null=True),
        ),
    ]
