# Generated by Django 6.0.3 on 2026-03-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_user_openai_api_key_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='video_limit',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=5, help_text='Maximum number of videos user can upload. 0 means no uploads allowed, null means unlimited.', null=True),
        ),
    ]
