# Generated by Django 6.0.3 on 2026-03-18 20:14

import app.infrastructure.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_user_video_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_video_upload_size_mb',
            field=models.PositiveIntegerField(default=app.infrastructure.models.user._default_max_video_upload_size_mb, help_text='Maximum video upload size in MB for this user.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='video_limit',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=app.infrastructure.models.user._default_video_limit, help_text='Maximum number of videos user can upload. 0 means no uploads allowed, null means unlimited.', null=True),
        ),
    ]
