# Generated by Django 6.0.3 on 2026-03-26 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_add_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='video_limit',
        ),
    ]
