# Generated by Django 6.0.3 on 2026-03-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_user_video_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='openai_api_key_encrypted',
        ),
    ]
