# Generated by Django 6.0.3 on 2026-03-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_user_openai_api_key_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_over_quota',
            field=models.BooleanField(default=False),
        ),
    ]
