# Generated by Django 6.0.3 on 2026-03-29 13:54

import app.infrastructure.models.video
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_subscription_is_over_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('youtube', 'YouTube')], db_index=True, default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_video_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, upload_to=app.infrastructure.models.video.user_directory_path),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['user', 'source_type', '-uploaded_at'], name='app_video_user_id_de5bbd_idx'),
        ),
    ]
