# Generated by Django 6.0.3 on 2026-03-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_video_source_type_video_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='searchapi_api_key_encrypted',
            field=models.BinaryField(blank=True, help_text='Encrypted SearchAPI API key', null=True),
        ),
    ]
