# Generated by Django 6.0.3 on 2026-04-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_videogroup_share_token_to_share_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_answers_limit',
            field=models.IntegerField(default=7000),
        ),
        migrations.AddField(
            model_name='user',
            name='is_over_quota',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='processing_limit_minutes',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='user',
            name='storage_limit_gb',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='unlimited_ai_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='unlimited_processing_minutes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='used_ai_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='used_processing_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='used_storage_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
