# Generated by Django 6.0.4 on 2026-04-26 13:44

from django.db import migrations, models


def migrate_unlimited_flags(apps, schema_editor):
    User = apps.get_model("app", "User")
    User.objects.filter(unlimited_processing_minutes=True).update(processing_limit_minutes=None)
    User.objects.filter(unlimited_ai_answers=True).update(ai_answers_limit=None)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_chatlog_retrieved_contexts_chatlogevaluation'),
    ]

    operations = [
        # 1. Make limit fields nullable first
        migrations.AlterField(
            model_name='user',
            name='ai_answers_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='processing_limit_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='storage_limit_gb',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        # 2. Convert unlimited flags → None in limit fields
        migrations.RunPython(migrate_unlimited_flags, migrations.RunPython.noop),
        # 3. Remove the now-redundant bool flags
        migrations.RemoveField(
            model_name='user',
            name='unlimited_ai_answers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unlimited_processing_minutes',
        ),
    ]
