# Generated by Django 6.0.4 on 2026-05-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_make_limits_nullable_remove_unlimited_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='pending email address'),
        ),
    ]
