# Generated by Django 6.0.4 on 2026-06-13 13:04

from django.db import migrations


def backfill_display_order(apps, schema_editor):
    VideoGroup = apps.get_model("app", "VideoGroup")
    user_ids = (
        VideoGroup.objects.order_by()
        .values_list("user_id", flat=True)
        .distinct()
    )

    for user_id in user_ids:
        groups = list(
            VideoGroup.objects.filter(user_id=user_id).order_by("-created_at", "id")
        )
        for index, group in enumerate(groups):
            group.display_order = index
        VideoGroup.objects.bulk_update(groups, ["display_order"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_videogroup_display_order"),
    ]

    operations = [
        migrations.RunPython(backfill_display_order, migrations.RunPython.noop),
    ]
