# Generated by Django 6.0.6 on 2026-06-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_backfill_videogroup_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='tool_trace',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
